### ISSUE TITLE
Cannot specify custom num_classes for pretrained SuhffleNetV2

### ISSUE THREAD

**Issue by mattans** [pytorch/vision#1040]
Code:

`from torchvision.models import shufflenet_v2_x1_0
model = shufflenet_v2_x1_0(pretrained=True, progress=True, num_classes=1)`

Error:
`RuntimeError: Error(s) in loading state_dict for ShuffleNetV2:
	size mismatch for fc.weight: copying a param with shape torch.Size([1000, 1024]) from checkpoint, the shape in current model is torch.Size([1, 1024]).
	size mismatch for fc.bias: copying a param with shape torch.Size([1000]) from checkpoint, the shape in current model is torch.Size([1]).`

So cannot load weights to the model, because the custom number output channel is different than the one used for training on ImageNet.
Perhaps if num_channels != 1000, replace the trained FC layer with a random FC layer but with correct dimensions?

My workaround is to give up num_classes and then call:
`    model.fc = Linear(in_features=model.fc.in_features, out_features=1, bias=(model.fc.bias is not None))`

**Comment by surgan12** [comment]
@mattans ,In your case since pretrained is true . I think, this should load the orignal model only and making such a change would not be a desired one.

**Comment by fmassa** [comment]
@mattans this is an explicit choice, because the way we replace the `classifier` is arbitrary, for example:
- just the last layer?
- re-use the weights from the common classes in the last layer?
- should we change the initialization for the random weights to something else?

Note that this is the same behavior for all other models in `torchvision`.
Your workaround is actually one of the recommended ways of doing it, as of now.
