### ISSUE TITLE
Area resizing in GeneralizedRCNNTransform 

### ISSUE THREAD

**Issue by juanmed** [pytorch/vision#1065]
Hello,

While working with the detection models released in 0.3, I noticed that in [GeneralizedRCNNTransform.py](https://github.com/pytorch/vision/blob/master/torchvision/models/detection/transform.py), while the image, bounding box coordinates, mask and keypoints are resized accordingly, the ```area``` field of the target dictionary is not resized. Is there any reason for not doing it? 

As far as I understand, not resizing the area while have an effect on the coco metrics. 

Resizing the area could be done using the resized bounding box coordinates
https://github.com/pytorch/vision/blob/05ba3f53d1a40f497d4af4768428b7fb1a8dd550/torchvision/models/detection/transform.py#L75

```python
        if "area" in target:
            target["area"] = (bbox[:, 3] - bbox[:, 1]) * (bbox[:, 2] - bbox[:, 0])
```

**Comment by fmassa** [comment]
@juanmed great question!

The COCO evaluation takes the area into account in order to perform the `small` / `medium` / `large` separation. If you scale the area, this will affect the results of the metrics in an unwanted way (you want to evaluate on the original image size).

But this doesn't have any effect I believe, because we do not use the `area` inside the model, and we rescale the images to the original image size in the end of `forward`.

**Comment by juanmed** [comment]
@fmassa Thanks for your explanation :) I understand then that resizing the ```area``` field is unnecessary, and adding would otherwise require to resize during postprocessing as well which seems unnecessary overhead. 

I will close this issue. Thanks!
