### ISSUE TITLE
Questions about transform in classification reference

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#1129]
These question refer to the transform of the validation dataset in the classification reference:

https://github.com/pytorch/vision/blob/8837e0efbe16dc07ccdd4f1d06460643c7b41c50/references/classification/train.py#L138-L145

- Are we resizing the images in order for the motifs to be roughly the same size?
- How was the number `256` chosen? Is this simply the next of power of 2 greater than `224`?

This was asked before in pytorch/examples#478 without a definitive answer.

**Comment by fmassa** [comment]
@pmeier those parameters have been around since AlexNet, and are the same ones that have been used for training. Check section 4.1 in https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks.pdf

Even though here we do not do the 5 crop validation, and we just take the center crop. Another valid approach would have been to rescale the image to be 224x224, but that would cause distortions on the aspect ratio of the objects.

> Are we resizing the images in order for the motifs to be roughly the same size?

Yes. Additionally, it also simplifies batching images together for faster inference.

We could avoid those crops and just perform inference on a single image at a time, while keeping the aspect ratio. I'm not sure how much we would gain / lose in accuracy due to that though.

Let me know if you have further questions
