### ISSUE TITLE
[BUG] VOC PASCAL is missing one image_set

### ISSUE THREAD

**Issue by lpuglia** [pytorch/vision#1237]
I was just trying out the new pytorch (1.2) and torchvision (0.4) when I encountered a problem in loading VOC `test` set, as you can see in the following locations:
https://github.com/pytorch/vision/blob/v0.4.0/torchvision/datasets/voc.py#L87
https://github.com/pytorch/vision/blob/v0.4.0/torchvision/datasets/voc.py#L164

the `verify_str_arg` is missing one valid dataset (the `test` one), adding `test` in the arguments solves the problem.

**Comment by pmeier** [comment]
According to the docstring

https://github.com/pytorch/vision/blob/a1ed206ff422f7e9a49c63d4b507ec3aa5fb770d/torchvision/datasets/voc.py#L61

`"test"` is not a valid argument for `image_set`. I'm not familiar with `VOC`, but in general we don't include the `test` split, since we have no labels for it.

**Comment by lpuglia** [comment]
The fact is that for VOC the labels for `test` are available alongside with the other `image_set`, they all have the same format and there is no point in not allowing them

**Comment by pmeier** [comment]
In that case, we should indeed include it. Could you open a PR?

**Comment by lpuglia** [comment]
here you are:
https://github.com/pytorch/vision/pull/1238

**Comment by lpuglia** [comment]
there are some little changes to make, i will make another PR
