### ISSUE TITLE
fasterrcnn_resnet50_fpn silent error

### ISSUE THREAD

**Issue by rkruegs123** [pytorch/vision#1247]
When you pass in bounding boxes for training that are beyond the dimensions of the images, no error is thrown.

**Comment by fmassa** [comment]
Hi,

Thanks for opening the issue!

This is something that I believe should be handled by the dataset itself though.

Indeed, what would we want to do in this case?
- Clamp the box to be within the image?
- Discard the box?
- Raise an error and stop training?
- Something else?

For example, in the COCO dataset in https://github.com/pytorch/vision/blob/a91fe7221b55c55dbbc23c23aecf33d470a5c08e/references/detection/coco_utils.py#L62-L66
we clamp the boxes to lie within the image, which is a deliberate decision on the **dataset** level, not the model.

Given that, I'd say that this behavior is intentional. But we can make it more explicit in the documentation that the boxes should be valid.

Let me know if you disagree.
