### ISSUE TITLE
resnet50 defined in torchvision/models/resnet.py is v1.5?

### ISSUE THREAD

**Issue by mingxiaoh** [pytorch/vision#1266]
hello, we checked the code, it seems that the resnet50 model defined in torchvision/models/resnet.py is actually v1.5? Would you please help confirm this issue?  

==================================
The difference between v1 and v1.5 is that, in the bottleneck blocks which requires downsampling, v1 has stride = 2 in the first 1x1 convolution, whereas v1.5 has stride = 2 in the 3x3 convolution.
===============================
        # Zero-initialize the last BN in each residual branch,
        # so that the residual branch starts with zeros, and each residual block behaves like an identity.
        # This improves the model by 0.2~0.3% according to https://arxiv.org/abs/1706.02677

**Comment by fmassa** [comment]
yes, torchvision implements resnet with the downsampling in the 3x3 convolution, so it is the 1.5v that you mention (although this is the first time I see this mentioned this way).

**Comment by tfboyd** [comment]
I "popularized" the name ResNet v1.5 which was used informally and internally at NVIDIA. I have never attempted to take credit because I did it to help standardize conversations for my own benefit. I believe Facebook was the first to use this tweak but did not give it a name beyond ResNet and implying v1.  http://torch.ch/blog/2016/02/04/resnets.html    I am not a researcher and wanting nothing to do with any weird taking of credit for simply pointing out the difference and the fact it matters. In old testing there was a 12% performance (throughput) difference and 5% inference.  With NVIDIA optimizing for v1.5 it is very possible the difference is not the same.
