### ISSUE TITLE
Master build error

### ISSUE THREAD

**Issue by jinfagang** [pytorch/vision#1278]
```
torchvision/csrc/cpu/nms_cpu.cpp:36:41: error: expected primary-expression before ‘>’ token
   auto areas = areas_t.data_ptr<scalar_t>();
                                         ^

```

**Comment by LukasBommes** [comment]
Same here. Python 3.7.1, Ubuntu 18.04, gcc version 7.4.0.

**Comment by jinfagang** [comment]
This should not happen I think..... we have everything needed flags enable C++11..... except..... syntax error...

**Comment by fmassa** [comment]
Since yesterday, torchvision master now requires a torchvision nightly, see https://github.com/pytorch/vision/pull/1262

**Comment by jinfagang** [comment]
I don't understand..... my pytorch is build from source which based on master.... shouldn't be nightly? Just pulled it yesterday.

**Comment by fmassa** [comment]
You might need to remove your previous installation of PyTorch and try installing it again, you might have some conflicts in there.

**Comment by rowanz** [comment]
hey all! so I found the same compilation issue when trying to install maskrcnn-benchmark from its provided [dockerfile](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/docker/Dockerfile). It automatically installs pytorch 1.0 nightly, and then torchvision master (the latter of which is where the error occurs).

I was able to get it to work (at least so far!!) with the following workaround: rather than install pytorch 1.0 nightly and torchvision master, I instead installed pytorch 1.2 and `torchvision==0.4.0a0+6b959ee` via the following command

`conda install pytorch torchvision cudatoolkit=10.0 -c pytorch`

hope that helps!
