### ISSUE TITLE
Inconsistent channels dimensions with VideoClip

### ISSUE THREAD

**Issue by ekosman** [pytorch/vision#1338]
When trying to retrieve a clip using:
```video, audio, info, video_idx = self.video_clips.get_clip(idx)```

sometimes the output i get is "channels last" and sometimes it's "channels first". Ofcourse, I could verify that by checking ```video.shape[-1] == 3``` and permute the dimensions if needed, but it can cause bugs for others so I think it should be consistent and use "channels first".

**Comment by fmassa** [comment]
This is not actually the case.

The output of `read_video` (and thus `VideoClips` is supposed to always be channels last.
We do have a transform to convert from channels first to channels last, see https://github.com/pytorch/vision/blob/6de158c473b83cf43344a0651d7c01128c7850e6/references/video_classification/transforms.py#L42-L43 and https://github.com/pytorch/vision/blob/6de158c473b83cf43344a0651d7c01128c7850e6/references/video_classification/transforms.py#L92-L94

As such, I'm closing this issue as is, but let me know if you think otherwise

**Comment by PHDPeter** [comment]
Hi 
So to be clear if I have a len(video.shape)=4 then the output is "channels last" correct?
if so which of the two functions above should I use to change the size to len(video.shape)=3 ?
(i.e. should I used ToFloatTensorInZeroOne(object) or to_normalized_float_tensor(vid) 0 
Sorry if this a very new question, I am just starting out with pytorch ect
Thanks
