### ISSUE TITLE
How trained this code  on data set fer2013?

### ISSUE THREAD

**Issue by akram-nejati** [pytorch/vision#1438]
I trained resnet on data set fer2013 with resnet  in tensor flow, but how training in code on pytorch and resnet?

**Comment by pmeier** [comment]
If you are unfamiliar with PyTorch (`torch`), I suggest you start with the [official tutorials](https://pytorch.org/tutorials/) to get a feel for it. Afterwards you can find the scripts that are used to train the models included in the `torchvision` package here:

https://github.com/pytorch/vision/tree/master/references

Since FER2013 is a classification dataset you can adopt

https://github.com/pytorch/vision/blob/master/references/classification/train.py

to fit your needs.
