### ISSUE TITLE
What's the advantage of torchvision.datasets.ImageNet?

### ISSUE THREAD

**Issue by Hou9612** [pytorch/vision#1504]
Hi I use torchvision==0.2.2 now and I'm hesitant to update torchvision. I am worried that updating torchvision may bring some unexpected problems. so I want to know what's the advantage of torchvision.datasets.ImageNet comparing with torchvision.datasets.ImageFolder?  Will it be faster when reading and processing ImageNet?

**Comment by surgan12** [comment]
Have a look here #713 specifically https://github.com/pytorch/vision/issues/713#issuecomment-456430169.

**Comment by pmeier** [comment]
By using the `ImageNet` dataset you will have the following advantages:

- After the download of the archives you don't need to manually prepare them for usage, i. e. you don't have to move the validation images in the appropriate folders
- The `ImageNet` object has the functionality of `ImageFolder.classes` and `ImageFolder.class_to_idx` implemented under `ImageNet.wnids` and `ImageNet.wnid_to_idx`. `ImageNet.classes` and `ImageNet.class_to_idx` have to same functionality but refer to the human-readable classes rather than the WordNet IDs.

Other than that the `ImageNet` dataset has no advantages over the `ImageFolder`. If you don't need or want the above properties you don't need to upgrade.

**Comment by Hou9612** [comment]
> Have a look here #713 specifically [#713 (comment)](https://github.com/pytorch/vision/issues/713#issuecomment-456430169).

Thanks, I'll have a look at it.

**Comment by Hou9612** [comment]
> By using the `ImageNet` dataset you will have the following advantages:
> 
> * After the download of the archives you don't need to manually prepare them for usage, i. e. you don't have to move the validation images in the appropriate folders
> * The `ImageNet` object has the functionality of `ImageFolder.classes` and `ImageFolder.class_to_idx` implemented under `ImageNet.wnids` and `ImageNet.wnid_to_idx`. `ImageNet.classes` and `ImageNet.class_to_idx` have to same functionality but refer to the human-readable classes rather than the WordNet IDs.
> 
> Other than that the `ImageNet` dataset has no advantages over the `ImageFolder`. If you don't need or want the above properties you don't need to upgrade.

Thanks, I think maybe I don't need to update it.

**Comment by fmassa** [comment]
Closing following @pmeier and @surgan12 comment
