### ISSUE TITLE
Training data set for pretrained resnet18

### ISSUE THREAD

**Issue by pantheon5100** [pytorch/vision#1591]
Anybody knows what the training data set of pretrained resnet18 is .
I cannot find the official information of training data set used for pretrained models in torchvision.models.

**Comment by pmeier** [comment]
The classification models, such as `resnet18`, models provided by PyTorch are trained with this script: 

https://github.com/pytorch/vision/blob/master/references/classification/train.py

If not noted otherwise, all models are trained on the [`ImageNet` dataset](https://github.com/pytorch/vision/blob/4b2f8daba9cca3d7cf003833c2e690d05afa2bf5/torchvision/datasets/imagenet.py#L19). For flexibility the dedicated class is not used there, but rather its super class: the [`ImageFolder` dataset](https://github.com/pytorch/vision/blob/4b2f8daba9cca3d7cf003833c2e690d05afa2bf5/torchvision/datasets/folder.py#L177). Given that you have a custom dataset in this structure, you can use it without modification of the reference script.

**Comment by pantheon5100** [comment]
@pmeier Thank you for your help.

**Comment by fmassa** [comment]
Closing following @pmeier comment. Thanks Philip!
