### ISSUE TITLE
Reference detection script image sizes help

### ISSUE THREAD

**Issue by gaussiangit** [pytorch/vision#1629]
Hi @fmassa , 
Somehow the reference detection script does not handle big images of size  > 3000. 
Always throw me cuda out of memory error. 
Any suggestions on that ?

**Comment by fmassa** [comment]
Big images are generally going to be a problem, because we forward through a batch of those images (generally 2 images per batch), and it is very memory intensive.

I don't think there is a magical fix for this -- I'd either recommend reducing the image size or passing crops of the image to the model.
