### ISSUE TITLE
torchvision fail to use GPU.

### ISSUE THREAD

**Issue by dihuangdh** [pytorch/vision#1723]
While I am using [detectron2](https://github.com/facebookresearch/detectron2), I meet the problem that some function in torchvision can't use GPU.

The details are here: https://github.com/facebookresearch/detectron2/issues/469

It seems an install problem. Directly using conda to install torchvision should be ok for most situations, but I am not sure whether this will lead to cuda usage error. 

Could you give some suggestions to fix this problem?  : )

**Comment by fmassa** [comment]
Hi,

I believe the issue is that you might have compiled torchvision on a different machine than the one that is executing the code.

One potential way of fixing it on your side would be to specify the GPU architectures that you want to compile torchvision.

From the torchvision cloned repo:
```
TORCH_CUDA_ARCH_LIST=6.0;6.1;7.0 python setup.py install
```

My recommended fix though is to use a conda installation for torchvision. You can install a nightly of pytorch and torchvision for that, which will have everything you need.
Once you re-install pytorch and torchvision, don't forget to clear the build files for detectron2 and install it again.

Let me know if you have further questions

**Comment by dihuangdh** [comment]
Hi,

Actually I did use conda installation for torchvision, but not work.

Also, I tried following command, but met the same problem.
```
TORCH_CUDA_ARCH_LIST=6.0;6.1;7.0 python setup.py install
```

**Comment by dihuangdh** [comment]
Is there any function to check the building cuda environment and running cuda environment of torchvision ?

**Comment by dihuangdh** [comment]
I have fixed the problem, by using matching version pytorch and torchvision. Thx !

**Comment by amajee11us** [comment]
How can we locate the matching version. I have verified the installation of pytorch and torchvision using conda and still it does not seem to work

**Comment by fmassa** [comment]
@amajee11us latest torchvision stable requires latest PyTorch stable, and latest nightly requires latest nightlies
