### ISSUE TITLE
[Bug?]  roialign operation returning incorrect numerics

### ISSUE THREAD

**Issue by coderAddy** [pytorch/vision#1875]
torchvision.ops.roialign is returning incorrect results for a simple test case-

```
# x: tensor of size (1,1,3,3)
x= torch.tensor([[[[1,2,3],[4,5,6],[7,8,9]]]], dtype=torch.float)
boxes = torch.tensor(([[0, 0, 2, 2, 0]]), dtype=torch.float)
z = torchvision.ops.roi_align(x, boxes, (2,2),sampling_ratio=1)


```

returns z as -
```
tensor([[[[7.5000, 8.5000],
          [7.5000, 8.5000]]]])
```

shouldn't this be
```
tensor([[[[3.0000 4.0000],
          [6.0000, 7.0000]]]])
```

**Comment by fmassa** [comment]
Hi,

It looks like your box is degenerate, as it's `y2` coordinate is smaller than the `y1` coordinate (it's `[roi, x1, y1, x2, y2]`.
In this case, the current implementation just clamps the box so that the dimension has at least a size of 1.

In `detectron2`, they implemented [an `aligned` version](https://github.com/facebookresearch/detectron2/blob/7fb05ed0f644214f1d631540ae7b6dffdb3c92e2/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.cpp#L149-L152), which in your case would just raise an error.

Given that this is a degenerate box case, I believe we should keep the current implementation as is for backwards-compatibility.

Let me know if you disagree.
