### ISSUE TITLE
roi_pool is seem to be different from which in FasterRCNN

### ISSUE THREAD

**Issue by SeniorCtrlPlayer** [pytorch/vision#1953]
```python
import torchvision
import torch

a = torch.linspace(1,8*8,8*8).reshape(1, 1, 8, 8)
boxes = torch.tensor([[0,0,3,3]],dtype=a.dtype)
out = torchvision.ops.roi_pool(a, boxes, output_size=(2,2))
```
i expect that out would be [[10 12],[26 28]]
but it's [[26 26],[26 28]]
and, i try more
```python
import torchvision
import torch
a = torch.linspace(1,8*8,8*8).reshape(1, 1, 8, 8)
boxes = torch.tensor([[1,1,3,3]],dtype=a.dtype)
out = torchvision.ops.roi_pool(a, boxes, output_size=(2,2))
```
out is 
[[4.373779945881600000e+15	4.373779945881600000e+15],
[4.373779945881600000e+15	4.373779945881600000e+15]]
that is so werid, i think roi_pool should be like [this](https://deepsense.ai/region-of-interest-pooling-explained/)

cc @fmassa

**Comment by fmassa** [comment]
Hi,

Thanks for the report. The issue is that you are wrongly passing `boxes` to `roi_align`: it should either be a `Nx5` tensor or a list of `Nx4` tensors.

You obtain the expected result if you do
```python
import torchvision
import torch

a = torch.linspace(1,8*8,8*8).reshape(1, 1, 8, 8)
boxes = torch.tensor([[0,0,3,3]],dtype=a.dtype)
out = torchvision.ops.roi_pool(a, [boxes], output_size=(2,2))
print(out)
```
which gives the expected result
```
tensor([[[[10., 12.],
          [26., 28.]]]])
```

This is something that I believe we should improve in the error checking, so that users have an error if they pass an unexpected input to the model.

I've opened a new issue to track this in https://github.com/pytorch/vision/issues/1957
