### ISSUE TITLE
have some problem when make torchvision

### ISSUE THREAD

**Issue by PKQ1688** [pytorch/vision#1963]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by adolf69** [comment]
/vision/torchvision/csrc/cpu/video_reader/FfmpegHeaders.h:4:10: fatal error: libavcodec/avcodec.h: No such file or directory
 #include <libavcodec/avcodec.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by fmassa** [comment]
Hi,

It looks like you don't have ffmpeg available in your system, or the include files are not in the expected directory.

Can you give more information about your system?

Also, if you don't need ffmpeg and the video reading functionality, you can just disable this branch https://github.com/pytorch/vision/blob/cca0c77a9ac5aa782b0811d850f246d73b0b4a1b/setup.py#L132
with a `False`, so that the video reading functionality won't be compiled.

Plus, we have recently fixed some issues with our nightly packages, so by tomorrow we should have new nightly packages available, so that you can avoid compiling torchvision yourself.

**Comment by adolf69** [comment]
thanks , I no need for ffmpeg at this time. I only use for image.

**Comment by datumbox** [comment]
This issue appears to be stale, so I'm closing it. If you think it should remain open, feel free to reopen it.

**Comment by qhaas** [comment]
Getting this error in torchvision 0.5 in EL8 (CentOS/Red Hat):
```
...
vision-0.5.0/torchvision/csrc/cpu/video_reader/FfmpegHeaders.h:4:10: fatal error: libavcodec/avcodec.h: No such file or directory
 #include <libavcodec/avcodec.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
```

But, clearly it is there:
```
$ locate avcodec.h
...
/usr/include/ffmpeg/libavcodec/avcodec.h
...
$  dnf list installed | grep ffmpeg | awk '{ print $1 }'
ffmpeg.x86_64
ffmpeg-devel.x86_64
ffmpeg-libs.x86_64
```

Solved via a hack, guessing Debian-like distros don't place these folders in /usr/include/ffmpeg:
```
pushd /usr/include
ln -s ffmpeg/libavcodec
ln -s ffmpeg/libavdevice
ln -s ffmpeg/libavfilter
ln -s ffmpeg/libavformat
ln -s ffmpeg/libavresample
ln -s ffmpeg/libavutil
ln -s ffmpeg/libpostproc
ln -s ffmpeg/libswresample
ln -s ffmpeg/libswscale
```

**Comment by fmassa** [comment]
@qhaas thanks for the report, we indeed need to improve the ffmpeg path finding scripts, which are for now not generic enough
