### ISSUE TITLE
Reminder: bytes is a valid type for torch._six.string_classes

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#2038]
This is a reminder for the following (from https://github.com/pytorch/vision/pull/2017#discussion_r400275068):

> [W]hy [do] we include `bytes` [in `torch._six.string_classes`] for [python3](https://github.com/pytorch/pytorch/blob/e3daf7018499fbcb52de4018543fd9a0306ccca6/torch/_six.py#L49)? For python2 `torch._six.string_classes` is simply [`basestring`](https://github.com/pytorch/pytorch/blob/e3daf7018499fbcb52de4018543fd9a0306ccca6/torch/_six.py#L47), which according to the [`six` documentation](https://six.readthedocs.io/index.html#six.string_types) is just `str` in python3.

@fmassa suggested:

> [...] it might be because we were dealing with output of a few IO functions in Python might be `str` or `bytes`, depending on how you opened the file.

---

Shouldn't this be an issue in [`torch`](/pytorch/pytorch) since it directly is related to `torch._six`?

**Comment by fmassa** [comment]
I think we can't change the behavior in `torch._six`, but if we do some careful inspection in the functions using `torch._six.string_classes` in torchvision, I believe we might need to remove some of those (or maybe all of them). The issue is that those code-paths are probably not tested by CI as of now, so it would make it slightly tricky to be 100% sure we are not breaking a few use-cases.
