### ISSUE TITLE
Documentation URL doesn't follow the patter

### ISSUE THREAD

**Issue by z-a-f** [pytorch/vision#2047]
## 📚 Documentation

You can get the `torchtext` documentation here: https://pytorch.org/text
`torchaudio` also has a similar URL: https://pytorch.org/audio
However, vision has a completely different URL: https://pytorch.org/docs/stable/torchvision

I think it is better to standardize the addresses, and make a common pattern https://pytorch.org/{package} for any `torch{package}`

**Comment by fmassa** [comment]
@jlin27 what do you think?

**Comment by jlin27** [comment]
I think standardizing the addresses makes sense, but first I think we'll need to check if there is a historical reason that vision was setup differently from text and audio. Do you know if there are any dependencies?

For background, the reason text and audio sites have that standard url is because they published using the [`gh-pages` method](https://help.github.com/en/github/working-with-github-pages/creating-a-github-pages-site), which means they are standalone sites built from the `gh-pages` branch of their respective repos. Also because of this, the url naming schema that's based off their repo name. 

While the docs for vision are part of the doc generation script for the rest of pytorch (rather than building it inside the pytorch/vision repo): https://github.com/pytorch/pytorch/blob/e67064a96f675bfffbae8e8a31701209435d66a2/.circleci/scripts/python_doc_push_script.sh#L60-L69

If there are no dependencies that vision must be build inside pytorch/pytorch, we could standardize this by generating pytorch/vision docs directly inside that repo and publishing to the `gh-pages` branch which would automatically give us the http://pytorch.org/vision url and we'd just add that url into the [index.rst here](https://github.com/pytorch/pytorch/blob/e67064a96f675bfffbae8e8a31701209435d66a2/docs/source/index.rst).

**Comment by fmassa** [comment]
I think this might just be due to historical artifacts, but I'll let @soumith chime in

**Comment by soumith** [comment]
it's historical.

I'm okay with harmonizing them in pytorch.org/vision , pytorch.org/text , pytorch.org/audio and providing a link to them in pytorch.org/docs
However, I worry that the people who use the search bar in pytorch.org/docs will start missing the results from before, so thinking that through is important

**Comment by z-a-f** [comment]
> it's historical.
> 
> I'm okay with harmonizing them in pytorch.org/vision , pytorch.org/text , pytorch.org/audio and providing a link to them in pytorch.org/docs
> However, I worry that the people who use the search bar in pytorch.org/docs will start missing the results from before, so thinking that through is important

Is it possible to setup a redirect?

**Comment by jlin27** [comment]
If we went that route, setup a redirect from pytorch.org/vision to https://pytorch.org/docs/stable/torchvision/ and keep the build as is, would @soumith be able to help with that redirect?

**Comment by soumith** [comment]
@jlin27 push an `index.html` page to vision's `gh-pages` branch that does the redirect.
Something like https://www.tutorialspoint.com/How-to-redirect-from-an-HTML-page

**Comment by jlin27** [comment]
@soumith - Maybe I'm misunderstanding, but I don't think vision has a `gh-pages` branch (https://github.com/pytorch/vision) since their docs are built directly inside of pytorch/pytorch docs build process. Would we need to setup a CNAME redirect?

**Comment by soumith** [comment]
it doesn't have a gh-pages branch, but you can create one, which will make `pytorch.org/vision` active and point to your created HTML page (in which you will point a redirect to https://pytorch.org/docs/stable/torchvision/index.html), which in turn will redirect users to https://pytorch.org/docs/stable/torchvision/index.html

**Comment by brianjo** [comment]
Thanks for the input. I'll set that up now.

**Comment by jlin27** [comment]
Thanks Soumith, we'll work on that.

**Comment by brianjo** [comment]
I have a PR ready, but the Create Pull Request button isn't enabled for me. 
Any ideas for what I need to do to fix? 
![Screen Shot 2020-04-14 at 9 45 13 AM](https://user-images.githubusercontent.com/1500149/79251430-f90d0280-7e34-11ea-97b3-e7813489820d.png)

**Comment by brianjo** [comment]
Figured it out. https://github.com/pytorch/vision/pull/2104

**Comment by brianjo** [comment]
https://pytorch.org/vision is working now.
Thanks all for your help on this. 

I'll close the issue.

**Comment by fmassa** [comment]
Thanks @brianjo !

**Comment by z-a-f** [comment]
Wouldn't it be better to have a redirect from `https://pytorch.org/docs/stable/torchvision` to `https://pytorch.org/vision`?

**Comment by fmassa** [comment]
@z-a-f I think from @soumith point before, that might have consequences with the search engine, but I'll let those with more experience in the documentation system to chime in
