### ISSUE TITLE
TorchVision Object Detection finetuning tutorial

### ISSUE THREAD

**Issue by develooper1994** [pytorch/vision#2088]
## 📚 Documentation

I am looking for object detection tutorial colab verison. I am getting error while training. I think error at "`evaluation or update or loadRes or createIndex`". I can't change. You should look at it

**Comment by fmassa** [comment]
Hi,

Thanks for the heads up. It looks like now Google Colab comes with a pre-installed version of `pycocotools`, which has a bug that has been fixed, see https://github.com/cocodataset/cocoapi/pull/354

In order to fix this issue for you, replace the first cell of the notebook with
```
pip install cython
pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
```
For some reason, installing with `python setup.py build_ext` doesn't seem to work anymore on colab.

I'll be sending a PR soon fixing the tutorials, thanks!

**Comment by fmassa** [comment]
This PR fixes the tutorial https://github.com/pytorch/vision/pull/2090
