### ISSUE TITLE
torchvision latest update(0.5.0) broke CosineAnnealingWarmRestarts: T_cur is not define

### ISSUE THREAD

**Issue by lironmo** [pytorch/vision#2119]
Hello,
maybe i missing something, but my tests failed on  CosineAnnealingWarmRestarts creation, 

the problem is:

        super(CosineAnnealingWarmRestarts, self).__init__(optimizer, last_epoch)

        self.T_cur = self.last_epoch

the super class call the override step function that use self.T_cur that is not defined.

**Comment by pmeier** [comment]
Hi,

1. `CosineAnnealingWarmRestart` is an `lr_scheduler` and implemented in `torch`. Your issue is betterr fitted to "their" [issue tracker](/pytorch/pytorch/issues).
2. Before you open a new issue, please compile a minimal example that clearly shows the problem you are facing. From what you have posted we can't reproduce your problem and thus in turn can't help you.

**Comment by lironmo** [comment]
1. ok.
2

**Comment by pmeier** [comment]
Is that what you meant?

```python
from torch import optim
from torch.optim import lr_scheduler
from torchvision.models import resnet50

model = resnet50()
optimizer = optim.SGD(model.parameters(), lr=0.05)
for param_group_dict in optimizer.param_groups:
    param_group_dict["initial_lr"] = param_group_dict["lr"]
lr_scheduler.CosineAnnealingWarmRestarts(
    optimizer=optimizer, T_0=50, T_mult=1, eta_min=0, last_epoch=0
)
```

If yes you can reduce this to 

```python
from torch import optim, nn
from torch.optim import lr_scheduler

model = nn.Conv2d(3, 3, 1)
optimizer = optim.SGD(model.parameters(), lr=1.0)
for param_group_dict in optimizer.param_groups:
    param_group_dict["initial_lr"] = param_group_dict["lr"]
lr_scheduler.CosineAnnealingWarmRestarts(optimizer=optimizer, T_0=1, last_epoch=0)
```

**Comment by lironmo** [comment]
Hi @pmeier, 
Thanks for your response,
I reported a bug in the right place and closed here.

As for upgrading the running example - the problem is not in the model and the size of the model does not really affect, on the other hand if it is easier for people I will try in the future to create leaner examples.

**Comment by pmeier** [comment]
> I reported a bug in the right place and closed here.

For cross reference: pytorch/pytorch/issues/36989

> on the other hand if it is easier for people I will try in the future to create leaner examples.

Please do that. By looking at your examples the following questions arose for me:
- Is this only happening for `resnet50`?
- Is the value of `lr` important?
- Are the values for `T_0`, `T_mult`, `eta_min`, and `last_epoch` important?

It turned out that only `last_epoch > -1` has an effect here. That is not all obvious from your example.

**Comment by lironmo** [comment]
you are right, but i want to be explicit of the value passed, and it's best to point about the problem if found.

thanks.
