### ISSUE TITLE
The batchsize of trainset using deform conv

### ISSUE THREAD

**Issue by XinMing0411** [pytorch/vision#2128]
### In my project, I want to use the deform conv，but there are some questions for us？

The deform conv which I use  is same as [demo](https://github.com/pytorch/vision/releases) .

When the batchsize of trainset <10,I can train the net without any problem.

But the batchsize of trainset>10, the project will raise a runtime error on optimizer [an illegal memory access was encountered].

I just change the size of batch, and do not change other

**Comment by pmeier** [comment]
Hi @XinMing0411 

please compile a minimal example, i. e. removing everything that is not needed to reproduce the error. Without seeing what exactly you are doing its almost impossible to help you.

**Comment by fmassa** [comment]
Hi,

What version of torchvision are you using?

We have fixed a few bugs in DeformConv2d with latest torchvision release, see https://github.com/pytorch/vision/pull/2027 and https://github.com/pytorch/vision/pull/2040

If the error still persists with torchvision 0.6.0 (released last week), can you please let us know and share a minimal reproducing script?

I'm closing the issue assuming that it has been fixed with the latest release of torchvision, but please let us know if that isn't the case
