### ISSUE TITLE
Vision 0.6 prerelease gets installes from pytorch channel in Anaconda

### ISSUE THREAD

**Issue by WaterKnight1998** [pytorch/vision#2133]
## 🐛 Bug

The release version is not getting installed in linux from anaconda pytorch channel. However, a prerelease version gets installed:

`0.6.0a0+82fd1c8`

**Comment by fmassa** [comment]
Hi,

Thanks for the report. When did you try downloading it? Also, how did you check the version, was it using `torchvision.__version__` or something else?

cc @seemethere maybe the `BUILD_VERSION` in https://github.com/pytorch/vision/blob/c031e2875bafe633cc163fb2bfe6c61f2f23285e/setup.py#L44-L48 is not working properly?

**Comment by seemethere** [comment]
So from what I can tell, the wheels produced get the correct version but the conda packages do not.

I think the issue stems from this commit: https://github.com/pytorch/vision/commit/490966f28ea6e11421d684e94cd995d6c53d4698

Particularly these lines:

https://github.com/pytorch/vision/blob/c031e2875bafe633cc163fb2bfe6c61f2f23285e/packaging/conda/build_vision.sh#L185-L214

This is where we override the upstream `BUILD_VERSION` from the `.cirlceci/config.yml` and replace it with something else.

As far as requiring a patch version it's not completely necessary since the git revisions are the same the version just looks weird.

We'll need to submit a patch to fix this for future releases though.

cc @peterjc123

**Comment by peterjc123** [comment]
@seemethere But this script is only used for Windows build. I removed all the logic for Mac/Linux so it shouldn't be the case.

**Comment by seemethere** [comment]
> @seemethere But this script is only used for Windows build. I removed all the logic for Mac/Linux so it shouldn't be the case.

You're absolutely right, I think it actually has to do with this

https://github.com/pytorch/vision/pull/1717/files#diff-2eeaed663bd0d25b7e608891384b7298R46-R47

We actually used to edit out the lines that append the SHA for previous versions which is't really the right thing to do.

I think the reason this was necessary is because the `BUILD_VERSION` environment variable doesn't actually get passed through the `meta.yaml` when the `conda build` gets done since it isn't included as a `script_env` variable.

I'll submit a PR to properly pass that and that should get us going with correct versions for all packages.

**Comment by WaterKnight1998** [comment]
> When did you try downloading it?

@fmassa I tried this morning! I checked with torchvision.__version__. However, with pip there was no issues at all!
