### ISSUE TITLE
Inception_v3 is not working

### ISSUE THREAD

**Issue by bisakhmondal** [pytorch/vision#2145]
## 🐛 Bug

I am dealing with classification tasks using torchvision's predefined models. Whenever I try to load the `inception_v3` API, the runtime gets stalled for infinitely. The problem persists for no matter if  I set `pretrained=True` or ` False`, whereas the other models are loading seamlessly.
** sometimes it gets loaded after a long time.
## To Reproduce

```python
from torchvision import models
model = models.inception_v3 ( )
model = models.inception_v3 (pretrained = True)
```

## Expected behavior

I think it would be better if it at least throws some error or message in this type of case.
It is somewhat working in `torchvision 0.4.1` && `torch 1.3.0`, though loading takes some time.
I have provided a **([link](https://colab.research.google.com/drive/1guyy6tHj3nkqrbFT97kD_vM2tlCpPtdO) )** to the colab notebook for further details.
## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.3
[pip3] torch==1.4.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.5.0
[conda] Could not collect

**Comment by fmassa** [comment]
Hi,

This is an issue with latest version of scipy, see related issues https://github.com/pytorch/vision/issues/1797 and https://github.com/pytorch/vision/issues/1977, and you can fix that with `init_weights=False` argument in inception.

I think given how recurrent this issue is now we should maybe consider changing the default weight initialization in `inception_v3`. I've opened an issue to track this down and improve this on torchvision https://github.com/pytorch/vision/issues/2166

**Comment by bisakhmondal** [comment]
Thanks for the response and the fix :+1: . Really appreciate it. :)
