### ISSUE TITLE
generate_anchors method in torchvision/models/detection/rpn.py is generating anchors with 1 / aspect_ratios instead of specified aspect_ratios

### ISSUE THREAD

**Issue by malhotraa** [pytorch/vision#2171]
## 🐛 Bug

[generate_anchors](https://github.com/pytorch/vision/blob/master/torchvision/models/detection/rpn.py#L77) method in rpn.py is generating anchors with 1 / aspect_ratios instead of specified aspect_ratios

## To Reproduce

* Call `generate_anchors` method with following input:
   scales: [32]
   aspect_ratios: [0.5]

* Output from above call is [-22, -11, 22, 11]. Assuming the coordinates are in format [xmin, ymin, xmax, ymax] the aspect ratio is (22/11) = 2 instead of 0.5 which we would expect.

## Expected behavior
The above method should produce anchors with specified aspect_ratios instead of 1/aspect_ratios

## Environment
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 418.39
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] numpy                     1.18.1                   pypi_0    pypi
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torchvision               0.5.0                    pypi_0    pypi

## Additional context
N/A

**Comment by fmassa** [comment]
This all depends on what is the definition of aspect ratio that you are considering. If it's `width / height` or `height / width`. It looks like unfortunately we decided to use the "wrong" definition of aspect ratio.

Given that changing the implementation would be a BC-breaking change, I propose that we add a note in the documentation clarifying that aspect ratio that we consider is `height / width`, instead of the more widely adopted `width / height`.

Could you send a PR improving the documentation?

**Comment by fmassa** [comment]
Fixed with https://github.com/pytorch/vision/pull/2185
