### ISSUE TITLE
Using `vision.references`

### ISSUE THREAD

**Issue by Sentient07** [pytorch/vision#2254]
Hi,

I was wondering if there was a way by which I can use the modules inside `vision.references`, especially `vision.references.detection.engine`'s `train_one_epoch` method. At the moment, I am unable to import and use it rather would have to copy-paste or download. Could this be simplified into an import? (by adding an `__init__.py`) ? Or, perhaps there is a way to do this more elegantly and I'm unaware? 

Thanks and Regards,

**Comment by fmassa** [comment]
Hi,

We have for now on purpose avoided adding it as part of torchvision library, because those are meant to be training scripts and the abstractions are specific to a particular task.

Plus, copy-pasting (or cloning locally) makes it easier to adapt / modify the training scripts for your own needs, by adding prints / breakpoints easily for debugging, and is the most flexible way without adding too much complexity.

Given that they are meant to be reference implementations, I think it might be preferable to keep it as is, instead of adding it into the torchvision library.

Let me know if you disagree.

**Comment by Sentient07** [comment]
Hi, @fmassa thanks for your reply. I am wondering whether there is an alternative way that is as easy and elegant as using some of the functions like `train_one_epoch`? It makes my training extremely simple, just a few lines without having to explicitly handle batches, epoch, and iterations. Furthermore, if I understand correctly, this function is not exclusive to a single model but any detection task that follows COCO's format, and hence it makes sense to me to have `engine.py` and `utils.py` publicly accessible if not all. Copy-pasting is not a big thing but importing, of course, is easier :)

**Comment by fmassa** [comment]
@Sentient07 having some functions be importable would definitely lower the bar for people to use it.

`train_one_epoch` is a bit generic and could be a candidate, but as you mentioned it is specific to our API for detection models. While it could make sense to have it exposed specifically for detection under `torchvision.engine.detection.train_one_epoch`, we would need to make it a bit more complicated to handle other use-cases, like exposing the print step, a `MetricLogger` engine, what metrics we want to log, etc. This can end up becoming quite complicated, while just copy-pasting and modifying it super simple.

That's one of the biggest reasons why I think might be preferable to avoid exposing it as a library function, as the added complexity might not be worth it, and we would end-up with something similar to ignite or pytorch-lightning.
