### ISSUE TITLE
ToTensor Changes C x H x W (5 x 600 x 900) to H x C x W (900 x 5 x 600)

### ISSUE THREAD

**Issue by sarmientoj24** [pytorch/vision#2318]
Here is my DataLoader. When I use ToTensor, it changes the dimensions of the image to H x C x W.
Not sure how to fix this

```
class DPWHDataset(Dataset):
  def __init__(self, mean=None, std=None, phase=None, dataset=None):
    self.data = dataset
    self.mean = mean
    self.std = std
    self.phase = phase
    self.transforms = get_transforms(phase, mean, std)
  
  def __len__(self):
    return len(self.data)

  def __getitem__(self, idx):
    image_name = self.data[idx]

    image_path = image_prefix + image_name + ".jpg"
    mask_path = binary_mask_prefix + image_name + "_mask.png"

    mask = cv2.imread(mask_path, 0)
    print(image_path)

    # image = np.array(Image.open(image_path))
    # mask = np.array(Image.open(mask_path))
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    
    mask = create_channel_mask(mask)
    # augmented = self.transforms(image=image, mask=mask)
    # image = augmented['image']
    # mask = augmented['mask']

    image = torchvision.transforms.ToTensor()(image)
    image = torchvision.transforms.Normalize(mean=self.mean, std=self.std)(image)
    mask = torchvision.transforms.ToTensor()(mask)
    return image, mask
```

cc @vfdev-5

**Comment by bmanga** [comment]
The documentation of ToTensor says:
> Converts a PIL Image or numpy.ndarray (H x W x C) in the range
    [0, 255] to a torch.FloatTensor of shape (C x H x W) in the range [0.0, 1.0]

So it seems like your input numpy array has the wrong dimensions. Unless you have a particular reason not to, I would just use PIL:
```
from PIL import Image
[...]
Image.open(abs_image_path).convert("RGB")
```

**Comment by pmeier** [comment]
@bmanga is correct, that `ToTensor` expects an image in the `HxWxC` format. I'm guessing OpenCV returns an image in the `CxHxW` format, which is than changed by `ToTensor` into `WxCxH`.

I suggest multiple changes that might make your life a little easier:

- Subclass your dataset from `torchvision.datasets.VisionDataset`. That enables a descriptive representation when you use `print(DPWHDataset())`
- Since the `transforms` should be independent of the dataset, they should not be created inside of it. If you subclass from `VisionDataset` you can simple use

   ```python
   if self.transforms is not None:
       image, mask = self.transforms(image, mask)
   ``` 
   in `__getitem__`.
- If there is no specific reason to use OpenCV, you can simply use `PIL` and `ToTensor` will handle the conversion for you without you needing to call `numpy`.

**Comment by fmassa** [comment]
Closing as stale and has already been answered.
