### ISSUE TITLE
DownSample

### ISSUE THREAD

**Issue by jianjiandandande** [pytorch/vision#2400]
https://github.com/pytorch/vision/blob/86b6c3e22e9d7d8b0fa25d08704e6a31a364973b/torchvision/models/resnet.py#L195

Why don't we need a downsample in this loop??

**Comment by fmassa** [comment]
Hi,

The original implementation of ResNet's only downsample at the first block of each layer. This way, the downsampling rate is a factor of the number of layers (always 4) instead of the number of blocks (which depends on the depth).
From the original paper https://arxiv.org/pdf/1512.03385.pdf
![image](https://user-images.githubusercontent.com/9110200/86758112-e9701500-c043-11ea-9489-1e0575bb3e05.png)
