### ISSUE TITLE
[RFC] Hardware-accelerated video decoding

### ISSUE THREAD

**Issue by bryandeng** [pytorch/vision#2439]
## 🚀 Feature
Hardware-accelerated video decoding

## Motivation
Now that torchscriptable transforms natively supporting GPU have landed, hardware-accelerated video decoding may further help relieve the IO bottleneck commonly seen in large-scale video deep learning tasks.

## Pitch
This functionality is likely to be built upon FFmpeg's hardware acceleration APIs, since FFmpeg is already in use and it's easier to support multiple hardware platforms and platform APIs in this way.

## Alternatives
[Decord](https://github.com/dmlc/decord) and [NVIDIA VPF](https://github.com/NVIDIA/VideoProcessingFramework) are both PyTorch-friendly video IO libraries which support (NVIDIA only) hardware-accelerated video decoding to some extent.
NVIDIA VPF is built upon NVIDIA Video Codec SDK directly without FFmpeg.

## Additional context
https://trac.ffmpeg.org/wiki/HWAccelIntro
https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

**Comment by fmassa** [comment]
Hi,

Thanks for opening the issue!

I agree that video decoding on the GPU would be a nice functionality to have, although it's not in the near-term plan for now (maybe in 6 months?).

About seeking on videos, we are preparing a revamp of the video reading abstractions which will be more generic and allow for more flexibility while performing video decoding. cc @bjuncek 

For video transformations on the GPU, note that we are making all transforms in torchvision to be torchscriptable and work with Tensors, so that they will natively support GPU if needed.

**Comment by bryandeng** [comment]
Updated description after the release of torchscriptable transforms.

**Comment by bryandeng** [comment]
We may first
- [ ] discuss which hardware platforms to support
- [ ] find out the constraints on input video formats and output pixel formats, etc.

**Comment by JuanFMontesinos** [comment]
Hi,
I wrote this small library which wraps ffmeg and does exactly that.
https://github.com/JuanFMontesinos/PyNVIdeoReader/tree/main
For those who need it, it can work in the meanwhile.

**Comment by dwrodri** [comment]
Pinging this thread to check for interest. Nvidia has been working on writing their own bridge between their GPU's encoders/decoders and popular machine learning libraries ([link here](https://github.com/nvidia/DALI)), but it's still in beta. Is there any interest in making this a feature in PyTorch? 

I could see something like this introducing some unintuitive edge cases, since an iterator that returns CUDA Tensors [may not play well with DataLoaders which leverage multiprocessing](https://pytorch.org/docs/stable/notes/multiprocessing.html). However, the goal of this feature addition would be to offer developers the option to leverage the Nvidia GPU decoders without installing another dependency. 

However, if the integration can be done from FFmpeg's C++ API, then it could probably be easily expanded to include Intel's and AMD decoder APIs as well, assuming they're all available form the same API.

**Comment by JuanFMontesinos** [comment]
I agree that it would be nice but it's not straight forward. The support varies a lot across different GPU models.
Besides, the video format is really specific: mp4 yuv 4:2:0 for decoding and mp4 420,422 or 444 for encoding (and depending on the gpu model)
More info [here](https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new#Encoder)

In short, if the user want to use GPU decoding it's really likely will have to prepare the videos beforehand. I find much simpler to pass a flag and let the user to fall in the codec exception if the format is wrong.

**Comment by JuanFMontesinos** [comment]
Let me just add that DALI's fixed-frame-rate support is not that bad. 
It allows to disect a video precisely ensuring proper seeking and audio-visual synchronization.
Different libraries address missing frames in different ways so that you can find they return different amount of frames.

**Comment by bjuncek** [comment]
If I understand correctly, the main drawback of GPU decoding are the lack of supported codecs? i.e. one would most likely need to prepare videos specifically for that? 
IMHO this is ok, as there has to be a speed/flexibility tradeoff. CPU decoding should not be deprecated regardless. 

 @JuanFMontesinos have you used DALI extensively for things like audio/video trainings? I'm interested if there are some weird/unexpected failure cases there, specifically with multiple modalities (streams) - in the past NVCODEC had some major issues with that, and I've been out of touch with it for the last year or so.

**Comment by JuanFMontesinos** [comment]
Hi @bjuncek 
So I'm just gonna talk about what I know, which is Nvidia's library. I don't know whether there is anything opensource or amd based.

So yes, the main drawback is nvidia only supports h264  (and h265 encoding from 30XX gen onwards).
I find it ok as the performance is really nice compared to cpu decoding. 

Soo In my experience DALI works really well as it optimizes resizing/cropping ops at the time of decoding the data (I'm not an expert, just metioning what i read in their docs)
Let me introduce a bit DALI just to have context.
Here is a short [tutorial](https://www.juanmontesinos.com/posts/2020/07/21/audiovisual-dali) for audiovisual loading.
In short they conceived DALI for traditional ML task aka: video classification, image classification, audio classification, segmentation or so.
The system is really well optimized as it relies on c++ loader which converts gpu data directly into pytorch's tensors.

The user doesn't have access to the streams, thus, I cannot make comments about it.
Just found that the performance is awesome and really fluid compared to CPU decoding. One saves the time of allocating the tensors on GPU and the optimization for cropping/resizing really matters.
Note that it works with constant framerate. No idea if the issues you found were related to variable framerate. However I find it convenient as it allows to do frame seeking by frame ID (rather than timestamps). This allows to recover any set of frames precisely (ensuring a perfect synchronization between streams).

Soo IMO it would be really awesome to adapt this to pytorch natively. A possible drawback I find is about pytorch's dataloader, which is python-coded and uses multiprocessing. I barely know that this would be problematic together with tensors allocated on gpu. So this may force to have a c++ decoder?

**Comment by bjuncek** [comment]
(copy from #4392)


I'm back after some time and have been doing some [benchmarking](https://github.com/bjuncek/video_reader_benchmark): 

<insert funny gif of an animal with lab equipment here>

In straight-up video reading, it is not obviously clear that GPU decoding is actually faster than CPU decoding [1]. 

In chat with some people that have tried it in their training pipelines, it seems like there is benefit of GPU decoding in end-to-end pipelines where decoded frames can be directly manipulated (transforms) and consumed (model) by the GPU. 
This raises the questions whether we can actually support this as our transforms are afaik done on CPU which means we'd actually have one additional memcopy to do. As @JuanFMontesinos mentions, I think a lot of in DALI performance comes from having this nicely integrated system, where everything is optimised. I'll be writing up some training code to see if I can properly test that in the following weeks.

Note that Mike from pyAV had similar thoughts and reasoning for not supporting HWAD in their docs [2]

![test](https://user-images.githubusercontent.com/6318056/135487200-7fdbfed0-38f0-47d9-85d1-3d296fb60afa.png)



[1] note, these comparisons were done on the machine with above-average CPU and what used to be quite competitive GPU. Running it on different hardware would probably provide more results. 

[2] https://pyav.org/docs/develop/overview/about.html : see section "Unsuported features"

**Comment by prabhat00155** [comment]
@bryandeng We added GPU video decoder recently. Detailed installation instructions can be found [here](https://github.com/pytorch/vision/tree/main/torchvision/csrc/io/decoder/gpu). It would be very helpful if you gave it a try and report any feedback you may have.

**Comment by bryandeng** [comment]
@prabhat00155 Thanks a lot! I will have a try.

**Comment by JuanFMontesinos** [comment]
Hi, I just remembered there is an Nvidia Toolkit 
https://github.com/NVIDIA/VideoProcessingFramework

Just pasting the description:

> VPF stands for Video Processing Framework. It’s set of C++ libraries and Python bindings which provides full HW acceleration for video processing tasks such as decoding, encoding, transcoding and GPU-accelerated color space and pixel format conversions.

>VPF also supports exporting GPU memory objects such as decoded video frames to PyTorch tensors without Host to Device copies. Check the [Wiki page](https://github.com/NVIDIA/VideoProcessingFramework/wiki/Building-from-source) on how to build from source.

Best
