### ISSUE TITLE
Why do we need target put .to(device)?

### ISSUE THREAD

**Issue by dmitrysarov** [pytorch/vision#2502]
Consider key points detection task.
The question refers to this line 
https://github.com/pytorch/vision/blob/1aef87d01eec2c0989458387fa04baebcc86ea7b/references/detection/engine.py#L86
Seems to be redundant.
In my case, I comment out this line and remove .item() in line 95, and at least evaluation starts.
Moreover, COCO dataset output is a tuple({'image_id': int, 'annotations': list(...)}) and I do not get it how it could work in 86 line.

**Comment by pmeier** [comment]
Hi @dmitrysarov 

https://github.com/pytorch/vision/blob/1aef87d01eec2c0989458387fa04baebcc86ea7b/references/detection/engine.py#L86

> Seems to be redundant.

You are right, this is not needed for the evaluation since the `targets` are not fed into the `model`. This seems to be a copy & paste error from the trainings loop, where this is needed:

https://github.com/pytorch/vision/blob/1aef87d01eec2c0989458387fa04baebcc86ea7b/references/detection/engine.py#L26-L30

Do you want to send a PR fixing this?

---

> Moreover, COCO dataset output is a tuple({'image_id': int, 'annotations': list(...)}) and I do not get it how it could work in 86 line.

Could you clarify what you mean?

**Comment by dmitrysarov** [comment]
> Could you clarify what you mean?

Sorry last part was my mistake, I miss understood functionality of https://github.com/pytorch/vision/blob/1aef87d01eec2c0989458387fa04baebcc86ea7b/references/detection/coco_utils.py#L50
It was not clear from the name that this function is mandatory for all tasks (including keypoint detection).

**Comment by fmassa** [comment]
Fixed by https://github.com/pytorch/vision/pull/2503
