### ISSUE TITLE
  File "/usr/local/lib/python3.6/dist-packages/torchvision/ops/feature_pyramid_network.py", line 53, in __init__     raise ValueError("in_channels=0 is currently not supported") ValueError: in_channels=0 is currently not supported

### ISSUE THREAD

**Issue by jinfagang** [pytorch/vision#2549]
```
  File "/usr/local/lib/python3.6/dist-packages/torchvision/ops/feature_pyramid_network.py", line 53, in __init__
    raise ValueError("in_channels=0 is currently not supported")
ValueError: in_channels=0 is currently not supported
```

How to fix this error in newest vision with older written style which I have a FPN start channel with 0.

```
in_channels_list = [
            0,
            in_channels_stage2 * 2,
            in_channels_stage2 * 4,
            in_channels_stage2 * 8,
        ]
        

        self.body = IntermediateLayerGetter(backbone, return_layers=return_layers)
        self.fpn = FeaturePyramidNetwork(
            in_channels_list=in_channels_list,
            out_channels=out_channels,
            extra_blocks=LastLevelP6P7(out_channels, out_channels),
        )
```

**Comment by fmassa** [comment]
Hi,

This is currently not supported, since we added torchscript support for faster r-cnn.

Contributions welcome!

**Comment by datumbox** [comment]
Thanks for reporting this @jinfagang. 

I had a look on this and it seems that the current recommended way of handling this is to pass the `returned_layers` argument with the layers you want to return, instead of putting zeros directly in the `in_channels_list` argument. 

Here are two examples of this approach in the repo:

**RetinaNet:**
https://github.com/pytorch/vision/blob/80f41f8d32b1fcb380d5df2116063af7034ff29a/torchvision/models/detection/retinanet.py#L625-L626

**ResNet_fpn:**
https://github.com/pytorch/vision/blob/80f41f8d32b1fcb380d5df2116063af7034ff29a/torchvision/models/detection/backbone_utils.py#L105-L108

And a custom usage snippet:
```python
import torch
from torchvision.models.detection.backbone_utils import resnet_fpn_backbone
backbone1 = resnet_fpn_backbone('resnet50', pretrained=True, returned_layers=[1,2,3,4])
backbone2 = resnet_fpn_backbone('resnet50', pretrained=True, returned_layers=[2,4])

x = torch.rand(1,3,64,64)

output = backbone1(x)
print([(k, v.shape) for k, v in output.items()])
#[('0', torch.Size([1, 256, 16, 16])), ('1', torch.Size([1, 256, 8, 8])), ('2', torch.Size([1, 256, 4, 4])), ('3', torch.Size([1, 256, 2, 2])), ('pool', torch.Size([1, 256, 1, 1]))]

output = backbone2(x)
print([(k, v.shape) for k, v in output.items()])
#[('0', torch.Size([1, 256, 8, 8])), ('1', torch.Size([1, 256, 2, 2])), ('pool', torch.Size([1, 256, 1, 1]))]
```

So you only need to adapt the way you pass the parameters. 

I'll close the issue, but if you have concerns please feel free to reopen it.
