### ISSUE TITLE
Allow hierarchy in ImageFolder dataset

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#2605]
## 🚀 Feature

Allow hierarchy in `ImageFolder` dataset.

## Motivation

Currently, `ImageFolder` (more specifically [`ImageFolder._find_classes()`](https://github.com/pytorch/vision/blob/5e9ebe8dadc0ea2841a46cfcd82a93b4ce0d4519/torchvision/datasets/folder.py#L124)) only scans for directories directly in `root`. This makes it impossible to use an `ImageFolder` for datasets that use a hierarchy in their image folders. 

An example for such a dataset is [`Places365`](http://places2.csail.mit.edu/index.html). It organizes the image folders by there first letters:

```
/a/airfield 0
/a/airplane_cabin 1
/a/airport_terminal 2
/a/alcove 3
/a/alley 4
/a/amphitheater 5
/a/amusement_arcade 6
/a/amusement_park 7
/a/apartment_building/outdoor 8
```

Sometimes a class also has one or multiple subclasses as can be seen in the last line.

## Pitch

We could add a `recurse=False` flag to the constructor of `ImageFolder`. If `recurse is True` it should not only scan the `root` directory but do this recursively for all sub-directories.

**Comment by fmassa** [comment]
Hi,

I think a `recurse` flag could potentially have some unexpected behavior in `DatasetFolder`, as `make_dataset` recurses inside the class folders itself https://github.com/pytorch/vision/blob/5e9ebe8dadc0ea2841a46cfcd82a93b4ce0d4519/torchvision/datasets/folder.py#L35-L62

Instead of passing a `recurse` argument, I think I would prefer if we subclass `DatasetFolder` and make `_find_classes` of the inherited class to perform the recursion inside.

Thoughts?

**Comment by pmeier** [comment]
I completely missed the `os.walk` in the top level folders. I was under the impression that only the top level folder is searched. 

Given that, I think I'll just implement the functionality I need separately in the dataset instead of using an `ImageFolder`. If some other dataset needs the same in future we can think of generalizing it then.
