### ISSUE TITLE
Incorrect types for functional adjust_hue

### ISSUE THREAD

**Issue by willprice** [pytorch/vision#2703]
## 📚 Documentation

![image](https://user-images.githubusercontent.com/966205/94044363-f0e2c700-fdc5-11ea-8249-e23bffaac103.png)

Method signature says `img` should be a tensor, but method parameters specifies it should be a PIL image. The latter is correct.

**Comment by fmassa** [comment]
Hi,

Thanks for opening the issue. This was a transient documentation issue that has been since then fixed in master.

TorchVision master now supports both Tensor and PIL images for its transforms. For torchscriptability reasons, the function signatures will only contain Tensor, while the documentation can state that they support both.

Check the new documentation in https://github.com/pytorch/vision/blob/1b41525443f8955487e5432743d346fa5c351ddf/torchvision/transforms/functional.py#L724-L748
which will be present in the next release of torchvision.

Given that this is fixed in master, I'm closing this issue, but thanks again for the heads up!

**Comment by willprice** [comment]
Ah, that's handy to know. Thanks @fmassa for the clear explanation :)
