### ISSUE TITLE
[Feature Request] More Image Transforms (Brightness, Contrast, Hue)

### ISSUE THREAD

**Issue by Kaixhin** [pytorch/vision#271]
It would be good to have some more image transforms (manual and random for augmentation). [TensorFlow has the following](https://www.tensorflow.org/api_guides/python/image#Image_Adjustments):

- Brightness
- Contrast
- Hue
- Gamma
- Saturation

**Comment by alykhantejani** [comment]
[a PR](https://github.com/pytorch/vision/pull/27/files) with some/most of these is already under review - we should look at getting that merged after #240 is merged.

**Comment by Kaixhin** [comment]
Didn't spot because I was searching for hue, so thanks for bringing up! Yes makes sense to revisit after both of these are merged in.

**Comment by chsasank** [comment]
@alykhantejani Shall I work on #27 and continue the PR?

**Comment by alykhantejani** [comment]
@chsasank the ones in #27 probably need to be re-worked a bit. I'll comment on that PR and see if the authors are willing to make the change. 

Do you want to start with Hue and Gamma (not present in #27) and then we can do the others (depending on the state of #27 then)?

**Comment by chsasank** [comment]
Sure. Any reference on the same? I've seen contrast, saturation transforms
but not gamma and hue. Thanks.

**Comment by Kaixhin** [comment]
[Automatic Portrait Segmentation for Image Stylization](http://xiaoyongshen.me/webpage_portrait/index.html) uses rotation, scale and gamma. [Do Deep Convolutional Nets Really Need to be Deep and Convolutional?](https://arxiv.org/abs/1603.05691) uses hue, saturation and value. I'm sure there are other papers out there, but I managed to find these two fairly quickly.

**Comment by alykhantejani** [comment]
@chsasank you can also use Tensorflow's implementation as a guide: https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/python/ops/image_ops_impl.py

**Comment by chsasank** [comment]
Thanks @Kaixhin, @alykhantejani ! TF implementation is really useful. I'll parrot function names and their parameters from there.

**Comment by fmassa** [comment]
@Kaixhin note that for Automatic Portrait Segmentation for Image Stylization, performing simple rotations actually harms performance of the final model (even if you take care of rotating and cropping the image such that no boundary artifacts are introduced due to rotation).
Random scale and crop helps a lot though, but having a large number of transforms that in the end do not contribute to the end performance (and even hurts performance) seems that might not be worth to it to me, as it can confuse users (who might thought that more transforms = better).

A few links showing that some transforms might not be helpful:
- https://github.com/facebook/fb.resnet.torch/issues/30#issuecomment-210542331
- https://github.com/pytorch/vision/pull/27#issuecomment-277920332

But we can extend the transforms if you think it's worth it.

**Comment by Kaixhin** [comment]
@fmassa it's true that naively throwing a lot of augmentations at data may hurt performance, but there are some cases where this extended set can help in particular. I'm currently looking at something where lighting conditions vary a lot 😰 As an example of where these augmentations have been used in practice, here's the [transformation code](https://github.com/chainer/chainercv/blob/master/chainercv/links/model/ssd/transforms.py) for  Single Shot Multibox Detector in ChainerCV.

**Comment by chsasank** [comment]
I raised PR with hue and saturation transforms at #275. Will add more if interested :)

**Comment by alykhantejani** [comment]
Closing as these we're addressed in #275
