### ISSUE TITLE
Clean up Assert Statements.

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/vision#2758]
2nd Follow-up of #2710.
As we discussed there, we use `Unittest` framework and not `pytest` though tests run via `pytest`.
We have some places in files [test_onnx.py](https://github.com/pytorch/vision/blob/master/test/test_onnx.py#L414)
and [test_ops.py](https://github.com/pytorch/vision/blob/master/test/test_ops.py#L436) (my bad tests as well).

Most were cleaned previously #1483

I guess I can clean then up, should I make a single PR or separate them one file at a time?

Also do let me know if there are additional places.

Also probably add this Uninttest framework tests a part of `contributing.md` file #2651 #2663 . It would probably avoid this `pytest` vs `Unittest` confusion.

**Comment by fmassa** [comment]
Hi @oke-aditya 

I think we don't have many more asserts left in the testing code, so a single PR should be fine (as long as there are not 100s of occurrences, if that's the case it's better to split in multiple PRs).

We currently work on both pytest and unittest, and that has traditionally been the case (except for maybe latest tests from @pmeier in https://github.com/pytorch/vision/blob/master/test/test_datasets_download.py ), and I would propose we keep it this way for now.

**Comment by pmeier** [comment]
The only thing `self.assertEqual()` and all the others methods do, is improving the error message of a plain `assert` when run from `unittest`. Since we are not doing that and instead run the test with `pytest`, they might even be detrimental: if `pytest` detects an `AssertionError` without custom message it provides a detailed introspection why the `assert` failed. Since the `unittest` methods use a custom message, the introspection is deactivated.

IMO, if we "force" a specific style, it should be `pytest` over `unittest`, since the former seems to become the de facto standard testing framework.

**Comment by fmassa** [comment]
@pmeier in torchvision we will follow whatever PyTorch uses, and PyTorch currently uses `self.assertEqual` and such.

**Comment by zhangguanheng66** [comment]
For torchtext, we use `self.assertEqual`, which is from `torch.testing._internal.common_utils` as pointed out above.

**Comment by mthrok** [comment]
@cpuhrsch once told me that PyTorch's `asserEqual` does more than giving a better error message, but also check other stuff (contiguous?) and there was some release related issue that PyTorch's`asserEqual` could have caught on PyTorch core. I forgot the detail but that convinced me to use PyTorch's `assertEqual`.

**Comment by pmeier** [comment]
Since this discussion "escalated" beyond `torchvision`, some clarifications: within our test suite we are **not** using [`torch.testing._internal.common_utils.TestCase`](https://github.com/pytorch/pytorch/blob/b1373a74e052ba482f021ce60a6b381fd0d40423/torch/testing/_internal/common_utils.py#L767) but rather plain [unittest.TestCase](https://docs.python.org/3/library/unittest.html#unittest.TestCase). While [`self.assertEqual()`](https://github.com/pytorch/pytorch/blob/b1373a74e052ba482f021ce60a6b381fd0d40423/torch/testing/_internal/common_utils.py#L1051) of the former indeed has additional functionality for `torch.Tensor`s, the latter [only provides better error messages](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertEqual).

**Comment by vincentqb** [comment]
> For torchtext, we use `self.assertEqual`, which is from `torch.testing._internal.common_utils` as pointed out above.

(same for torchaudio)

**Comment by fmassa** [comment]
I think we would like to use `torch.testing._internal.common_utils.TestCase` in torchvision. This was [not exposed in PyTorch lib the past](https://github.com/pytorch/pytorch/pull/30445), and thus we had to copy [our own variants in `common_utils.py`](https://github.com/pytorch/vision/blob/87c7864122e693948fee87c1a936c5b674c8a9b9/test/common_utils.py#L86-L87), which has a few copy-paste from [`common_utils.py` from PyTorch](https://github.com/pytorch/pytorch/blob/adc21c6db278829797161ff23a92e40068f0db5c/torch/testing/_internal/common_utils.py).

We have been manually implementing tensor comparison across our transforms via `(tensor1 - tensor2).abs().max() < TOL`, it would have been much better to just use PyTorch's implementation of `self.assertEqual`.

**Comment by datumbox** [comment]
Is this ticket still needed?

**Comment by pmeier** [comment]
Nope. Since we migrated to `pytest`, `self.assertEqual` is no longer a possibility and thus the discussion is moot. I'll leave it to Nicolas to close it though in case I missed something.

**Comment by NicolasHug** [comment]
thanks for the ping, yes we can close it. We now use `assert_close / assert_equal` for tensors-like object, and plain `assert` for everything else :)
