### ISSUE TITLE
Fix the documentation/readme

### ISSUE THREAD

**Issue by chsasank** [pytorch/vision#284]
Right now following are the ways to look up documentation is 
1. Part of pytorch docs: http://pytorch.org/docs/master/torchvision/torchvision.html
2. Readme.md.

Issue with these:
1. This is a sphinx build.Any new functions/classes requires 2 PRs. One here and another in pytorch/pytorch as source for docs are in that repo. 
2. Readme is not automatically updated. 

Somehow this needs to be fixed.

My solution:
Move `docs/torchvision/*` from pytorch/pytorch to this repo and build docs using autobot to gh-pages so that `pytorch.org/vision` shows torchvision's documentation.

(Only?) problem with this solution: Existing links to vision's docs in pytorch.org/docs will be broken.
 
 I think same can be done for torchtext. Proper sphinx website is sorely missing for torchtext.

PS. I'm willing to make the move if my solution looks fine to you, although I'll need help with autobot :)

**Comment by fmassa** [comment]
I don't have much experience with the documentation, but I think this looks very good to me!
torchvision documentation has always been a bit lagging behind pytorch's because it's not generated automatically, so it would be awesome if we could have that.

I think we can fix the broken links once this has been setup.

cc @soumith because he has setup the documentation generation for pytorch, so he definitely knows the details of it.

**Comment by soumith** [comment]
what's the value in making the docs separate?
cant we simply make it be pushed to pytorch.org/docs as it's done now but have the docs always be up to date / autogenerated?

(btw this PR is awesome)

**Comment by chsasank** [comment]
Actually that's a cool idea. We can have these docs pushed to http://pytorch.org/docs/torchvision/ instead of pytorch.org/vision. You can see the built docs at https://chsasank.github.io/vision/.

We should separate torchvision docs from pytorch/pytorch though.
