### ISSUE TITLE
Provide speed benchmarks for the new video reader API

### ISSUE THREAD

**Issue by fmassa** [pytorch/vision#2941]
## 📚 Documentation

It would be useful to provide some speed benchmarks of the `VideoReader` API somewhere in the documentation.
This has been requested twice already (once in https://github.com/pytorch/vision/issues/2934 and once by @takatosp1 ).

cc @bjuncek

**Comment by bjuncek** [comment]
Hi @fmassa,
do you have a suggestion to where I should be putting this in the docs (and which format - graphs, tables)?

Please find the attached per-frame decoding speed comparison (averaged over 100 decoding runs) in two scenarios:
1) Reading the entire video

a) averaged over all videos in our test suit
![reader_pervideo](https://user-images.githubusercontent.com/6318056/98025735-00f8b800-1e02-11eb-8761-3e77d210675e.png)

b) and for every video in our test suite
![reader_videos](https://user-images.githubusercontent.com/6318056/98025841-2259a400-1e02-11eb-9023-28e38dcada57.png)

2. Seek and decode set number of frames. Here we seek into a random point in the video and read 10 frames from that timestamp. Note that `pyav` doesn't allow this functionality in a reliable fashion. Instead, it seeks to the closest keyframe before the asked timestamp, and then needs to decode frames until we hit the timestamp we want and then decode 10 following frames. 

a) averaged over all videos in the test suit
![reader_seek_avg](https://user-images.githubusercontent.com/6318056/98026676-64cfb080-1e03-11eb-90b3-cffac7a1361e.png)


b) and for every video in our test suite
![reader_seek_videos10fms](https://user-images.githubusercontent.com/6318056/98026689-6a2cfb00-1e03-11eb-9c90-7239ea127228.png)

**Comment by fmassa** [comment]
> Note that pyav doesn't allow this functionality in a reliable fashion

Does this mean that those numbers aren't comparable?

**Comment by jgbradley1** [comment]
Was implementing [Decord](https://github.com/dmlc/decord) ever considered as a video loader option? It reports speeds that are around 2x faster than OpenCV or pyav.

**Comment by fmassa** [comment]
@jgbradley1 we would like to keep as a requirement that the operators are torchscriptable, so that they can easily be sent from Python to C++.

For us to be able to use Decord, we would have needed to rely on their internal C++ implementations, which they don't expose as a library, and modify them so that they can be torchscripted.

**Comment by bjuncek** [comment]
>> Does this mean that those numbers aren't comparable?

No, that means that the functionality had to be implemented in python. This is the way to get the same results from pyav that you'd get from VideoReader

**Comment by rgommers** [comment]
> do you have a suggestion to where I should be putting this in the docs

It's usually a good idea to keep the API reference docs separate from more narrative documentation. Currently there is no other documentation than API reference docs. 

Another issue is that benchmark results typically depend on build options used and on installed dependencies (see e.g. the Pillow vs. Pillow-SIMD note in the README). Due to that it's not common for projects to put benchmark results inside their docs.

If you do want it in the docs after all, I'd recommend:
- A separate top-level section in the Sphinx `toctree`, and link to that from the reference docs for `torchvision.io`.
- Store numerical values of the benchmarks in the repo, as either csv files or (if it needs to be smaller) as `.npy` files.
- Figures are more informative, so generate the figures within the doc build with a script.
- Be comprehensive in reporting the build settings and installed dependencies for the used results. For example, let the benchmark script store the output of `conda list`, and then parse that output during doc build.
- Consider adding to the release procedure that benchmark results should be regenerated before creating a new release branch.

**Comment by bjuncek** [comment]
Closed as it is a part of documentation #3460
