### ISSUE TITLE
Are these 2 lines of code necessary?

### ISSUE THREAD

**Issue by jc-hou** [pytorch/vision#3184]
Hi,
https://github.com/pytorch/vision/blob/master/references/video_classification/train.py#L134
https://github.com/pytorch/vision/blob/master/references/video_classification/train.py#L169

I wonder if these two lines are necessary.
Why do we need to assign transforms to dataset after loading them from cache, whose transforms have been declared when being saved.
I remove them and code seems still work.
Thanks.

**Comment by datumbox** [comment]
@jc-hou Good question. I think you are right. As far as I can tell it's not needed and here is a snippet to prove it:
```python
import torch
import torchvision

d = torch.utils.data.Dataset()
d.blah = 1
d.tfm = torchvision.transforms.Compose([torchvision.transforms.Resize(100)])

torch.save(d, "d.pt")
d = torch.load("d.pt")

print(d.blah)
print(d.tfm.transforms[0].size) 
```

@fmassa I git blamed it and I see that this was introduced at #1180 but I don't see any comments on why it's there. Maybe it was there to address a limitation in an earlier version of PyTorch. Could you confirm that this is no longer necessary?

**Comment by fmassa** [comment]
Hi,

So those two lines are actually needed if we save with the cache, as the cache also stores the transforms. The problem is if we modify the `image_size` or add new transforms to the script, the cache will still pick the old ones, potentially leading to subtle bugs.

This is also something that we should fix in the classification scripts, as we have some models (inception / googlenet) that uses larger resolution images and the default cache is not valid here.

Truth being said, it would have just been better to have a better caching system, but that would be a bit more involved and I just went with the simplest approach.

**Comment by jc-hou** [comment]
get it, thank you for the reply.
