### ISSUE TITLE
How to train a classifier with custom class num while also want pretrain=True?

### ISSUE THREAD

**Issue by jinfagang** [pytorch/vision#3547]
It will gives an error:

```
	size mismatch for fc.weight: copying a param with shape torch.Size([1000, 1024]) from checkpoint, the shape in current model is torch.Size([42, 1024]).

```

**Comment by frgfm** [comment]
@jinfagang Hey there :wave: 

You need to re-instantiate the corresponding layer as you cannot map the pretrained weights between the two (you thus need to train it as well to get proper results). Here is a short example:

VGG16 is trained on ImageNet and thus has 1000 outputs classes by default:
```
>>> from torchvision.models import vgg16
>>> model = vgg16(pretrained=True)
>>> print(model.classifier)
Sequential(
  (0): Linear(in_features=25088, out_features=4096, bias=True)
  (1): ReLU(inplace=True)
  (2): Dropout(p=0.5, inplace=False)
  (3): Linear(in_features=4096, out_features=4096, bias=True)
  (4): ReLU(inplace=True)
  (5): Dropout(p=0.5, inplace=False)
  (6): Linear(in_features=4096, out_features=1000, bias=True)
)
```
As shown above, the last Linear layer was designed and trained with 1000 output nodes. So back to your question, you have two options:

1 - Instantiate a VGG16 with 42 classes and train it from scratch
```
>>> from torchvision.models import vgg16
>>> model = vgg16(pretrained=False, num_classes=42)
```

2 - Instantiate a pretrained VGG-16 with 1000 classes, and modify the last layer (so that you only one layer "from scratch")

```
>>> from torch import nn
>>> from torchvision.models import vgg16
>>> model = vgg16(pretrained=True)
>>> model.classifier[6] = nn.Linear(model.classifier[6].in_features, 42)
>>> print(model.classifier)
Sequential(
  (0): Linear(in_features=25088, out_features=4096, bias=True)
  (1): ReLU(inplace=True)
  (2): Dropout(p=0.5, inplace=False)
  (3): Linear(in_features=4096, out_features=4096, bias=True)
  (4): ReLU(inplace=True)
  (5): Dropout(p=0.5, inplace=False)
  (6): Linear(in_features=4096, out_features=42, bias=True)
)
```

I would strongly suggest going with option 2, which is very common in deep learning!
Let me know if you have any questions :ok_hand:

**Comment by pmeier** [comment]
Hey @jinfagang, @frgfm answer is the way to go. As such, I'm closing this. If it does not solve your problem, feel free to reopen this.
