### ISSUE TITLE
coco_eval and coco_utils necessary to import

### ISSUE THREAD

**Issue by ollenordesjo** [pytorch/vision#3630]
## 📚 Documentation

I am following the instructions here: https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html
After running

I am getting this error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-20-5efce9759b86> in <module>
      3 import transforms as T
      4 import utils
----> 5 import engine

~/git/ont-bonito/notebooks/engine.py in <module>
      6 import torchvision.models.detection.mask_rcnn
      7 
----> 8 from coco_utils import get_coco_api_from_dataset
      9 from coco_eval import CocoEvaluator
     10 import utils

ModuleNotFoundError: No module named 'coco_utils'
```

It seems like the instructions to also copy over coco_utils and coco_eval to the working directory is missing:

Suggested change:

**Before:**
In references/detection/, we have a number of helper functions to simplify training and evaluating detection models. Here, we will use references/detection/engine.py, references/detection/utils.py and references/detection/transforms.py. Just copy them to your folder and use them here.

**After:**
In references/detection/, we have a number of helper functions to simplify training and evaluating detection models. Here, we will use references/detection/engine.py, references/detection/utils.py, references/detection/transforms.py, references/detection/coco_eval.py and references/detection/coco_utils.py. Just copy them to your folder and use them here.

**Comment by NicolasHug** [comment]
Thanks for the report

The note about installing `pycocotools` could indeed be clearer, as for now they only provide instruction for Windows.

Regarding the imports: it might be safer to tell users to copy the entire directory content, instead of a subset of files (there aren't many files anyway). The reason is that the "No module named ..." issue will happen again if we refactor that code into subfiles.

Would you like to submit a PR @ollenordesjo ?

I think it should be submitted to the tutorial repo as the file is https://github.com/pytorch/tutorials/blob/master/intermediate_source/torchvision_tutorial.rst (feel free to ping me there)

**Comment by ollenordesjo** [comment]
Thanks! Yes, I think it would make plenty of sense to just copy the entire directory as well. I'll submit a PR to that repo (thanks for pointing me to it!)

**Comment by NicolasHug** [comment]
https://github.com/pytorch/tutorials/pull/1462 was merged so we can close this one
