### ISSUE TITLE
Version of densenet

### ISSUE THREAD

**Issue by haofanwang** [pytorch/vision#391]
May I ask what's the version of densenet in torchivision.models ? The original or [efficient_densenet_pytorch](), as the original is memory hungry. If it's the original version, would pytorch team consider add the efficient version into model zoo ?

**Comment by soumith** [comment]
we plan to add a memory efficient version soon via https://github.com/pytorch/pytorch/pull/4594

**Comment by gpleiss** [comment]
Now that PyTorch 0.4 is officially out, I'm making the [efficient_densenet_pytorch](http://github.com/gpleiss/efficient_densenet_pytorch) code use the checkpointing feature. I can make a PR to this repo once I get it working!

**Comment by fmassa** [comment]
@gpleiss that would be a nice addition! Maybe by specifying a constructor argument that dispatches to `checkpoint`? The only thing we need to keep in mind is that `checkpoint` currently requires the input to have `requires_grad=True`, which is suboptimal in cases where we don't checkpoint.

**Comment by gpleiss** [comment]
@fmassa I'm thinking something like this?

```python
# prev_features = [feat_1, feat_2, ...]
# ...
 if self.efficient and any(prev_features.requires_grad):
    bottleneck_output = checkpoint(bn_function, *prev_features)
 else:
    bottleneck_output = bn_function(*prev_features)
# ...
```

**Comment by fmassa** [comment]
That sounds good!

**Comment by gpleiss** [comment]
So sorry for the late response this...

The efficient densenet code seems to work great on a single GPU. However, on multiple GPUs with nn.DataParallel, @wandering007 points out that the checkpointing feature is quite slow (see https://github.com/gpleiss/efficient_densenet_pytorch/issues/36). I think this is because checkpointing requires some sort of inter-GPU synchronization.

I'm opening up an issue in PyTorch about this. I'm holding off on a PR for now.

**Comment by fmassa** [comment]
Sounds good, thanks @gpleiss !
