### ISSUE TITLE
Meaning of Assertion of infer_scale function in  torchvision/ops/poolers.py

### ISSUE THREAD

**Issue by teang1995** [pytorch/vision#3949]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
I want to know the meaning of the assert at infer_scale function in  torchvision/ops/poolers.py.
![image](https://user-images.githubusercontent.com/23451721/120587728-dee71700-c470-11eb-8057-0d26a9afdfd1.png)

It makes assertion error 

  File "/home/ubuntu/.jupyter/engine.py", line 199, in evaluate_one_image
    output = model(loader)
  File "/home/ubuntu/.venv/jupyter/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.venv/jupyter/lib/python3.6/site-packages/torchvision/models/detection/generalized_rcnn.py", line 98, in forward
    detections, detector_losses = self.roi_heads(features, proposals, images.image_sizes, targets)
  File "/home/ubuntu/.venv/jupyter/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.venv/jupyter/lib/python3.6/site-packages/torchvision/models/detection/roi_heads.py", line 752, in forward
    box_features = self.box_roi_pool(features, proposals, image_shapes)
  File "/home/ubuntu/.venv/jupyter/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.venv/jupyter/lib/python3.6/site-packages/torchvision/ops/poolers.py", line 221, in forward
    self.setup_scales(x_filtered, image_shapes)
  File "/home/ubuntu/.venv/jupyter/lib/python3.6/site-packages/torchvision/ops/poolers.py", line 182, in setup_scales
    scales = [self.infer_scale(feat, original_input_shape) for feat in features]
  File "/home/ubuntu/.venv/jupyter/lib/python3.6/site-packages/torchvision/ops/poolers.py", line 182, in <listcomp>
    scales = [self.infer_scale(feat, original_input_shape) for feat in features]
  File "/home/ubuntu/.venv/jupyter/lib/python3.6/site-packages/torchvision/ops/poolers.py", line 166, in infer_scale
    assert possible_scales[0] == possible_scales[1]
AssertionError

like this, and without assertion it makes correct results.
what's the meaning of that assertion?

**Comment by datumbox** [comment]
Good question. I'm not the author of this method, but my understanding is that the `infer_scale()` uses the heuristic approach described on the [FPN paper at section 4.2](https://arxiv.org/pdf/1612.03144.pdf) to find to which level `Pk` of the pyramid we should assign the RoI. The implementation seems to use a different but equivalent formulation comparing to the equation used on the paper which in theory can lead to different `k` levels for each width and height values. It's unclear why it's implemented like that but perhaps it's done as a way to try to extend equation 1 of the paper to arbitrary size input (without the 224 size hardcoded). Unfortunately even with this expansion, we still need to ensure that at the end we have only one `k` value for width and height, hence the assert.

@fmassa You seem to be the author behind the PR. Do you remember the details? Why do we loop in each dimension instead of estimating a single `k` using the areas (aka be closer to the equation 1 of the paper)?

**Comment by teang1995** [comment]
@datumbox 
Thank you for answering my question.

I have one more question.  What kind of problem do you expect to occur without this assertion?
I have some pictures make assertion error there, but i cannot find common feature of them.

**Comment by datumbox** [comment]
The scaling parameter that is being estimated there is being used in a few places, for example here:
https://github.com/pytorch/vision/blob/c8f7d772e844d707e152e2a1fa1aad26cf1b7530/torchvision/ops/poolers.py#L186-L192

and here:
https://github.com/pytorch/vision/blob/c8f7d772e844d707e152e2a1fa1aad26cf1b7530/torchvision/ops/poolers.py#L226-L231

So it affects the structure of your network and the way the operations are executed. If you remove the assert and the heigh and width scales don't match then the second one will be ignored effectively. See:
https://github.com/pytorch/vision/blob/c8f7d772e844d707e152e2a1fa1aad26cf1b7530/torchvision/ops/poolers.py#L166

**Comment by teang1995** [comment]
Thank you for answering my question.
Have a good day!

**Comment by fmassa** [comment]
Hi,

I think this type of error could happen if for some reason one of the sizes of the image get squashed to 0 when doing the division of `img_size // scale`, maybe in a case of a very wide or narrow image maybe?
