### ISSUE TITLE
VideoResNet object is not iterable

### ISSUE THREAD

**Issue by SungmanHong** [pytorch/vision#4084]
```
  File "train_total.py", line 145, in __init__
    self.CNNlayers_front = nn.Sequential(*list(torchvision.models.video.r3d_18(pretrained=False)))
TypeError: 'VideoResNet' object is not iterable
```

How can I resolve this??

**Comment by NicolasHug** [comment]
Hi @SungmanHong , I'm wondering, did you encounter that issue with some code within torchvision? I cannot find a similar entry in our code.

Regardless, the code should be `nn.Sequential(*[torchvision.models.video.r3d_18(pretrained=False)])` or since there's only one argument, it can also be simplified to `nn.Sequential(torchvision.models.video.r3d_18(pretrained=False))`
