### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.fx'

### ISSUE THREAD

**Issue by wmpauli** [pytorch/vision#4886]
### 🐛 Describe the bug

I get this import error on
```
import torchvision.transforms as transforms
```

### Versions

Versions:
torch-1.6.0-cp36-cp36m-manylinux1_x86_64.whl
torchvision-0.11.1-cp36-cp36m-manylinux1_x86_64.whl

I think this happened since upgrading to v11.1. Reverting to v0.10.1 to confirm.

**Comment by wmpauli** [comment]
yes, reverting torchvision to v0.10.1, fixed the import error.

**Comment by fmassa** [comment]
@wmpauli note that torchvision 0.11 requires PyTorch 1.10. So many of the features in torchvision are not guaranteed to work correctly with an older PyTorch (for example, custom operators like `roi_align`).

Also, ccing @datumbox as it was at some point considered to make this a hard failure -- use-cases like this one would fail if we were to enforce loading the libraries to be a hard-requirement.

**Comment by datumbox** [comment]
Thanks for the ping. Indeed if @wmpauli was trying to call a C++ op, they would receive an error while using Python operators may or may not lead to an issue. Here the user got an error because the fx namespace doesn't exist in the previous version of PyTorch. 

@fmassa What was the reason we didn't make it a hard failure? We could add an assertion on the `torchvision/__init__.py` to cover for that.

**Comment by wmpauli** [comment]
Thanks again @fmassa and @datumbox. Like I mentioned above, reverting torchvision to .10.1 indeed avoids this issue. 

This is for the continuous deployment of an older model, which requires an older version of torch, so I had been pinning the version of pytorch to 1.6, relying on pip to resolve the versions of dependencies (including torchvision). I'll be more careful next time.
