### ISSUE TITLE
What's purpose of logging?

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/vision#4957]
### 🐛 Describe the bug

What is the purpose of logging? Is it going to auto-upload usage statistics somewhere?

Regarding implementation, what is the reason for not just doing it in a separate file or at least with a decorator? Currently it pollutes the library code during code browsing, especially for simple small functions. It also hurts copy-pasteability, as one needs to delete all this logging unnecessary for small copied snippets.

### Versions

It would also be nice to make this field not required. Often, there is no specific version. Core PyTorch also doesn't force entering version.

**Comment by kazhang** [comment]
Hi @vadimkantorov , thanks for reporting! The purpose of logging is that when PyTorch is used in a custom build environment (e.g. Meta), it's useful to track usage of various APIs centrally. For users outside of the organization, this is [a no-op](https://github.com/pytorch/pytorch/blob/eb3b9fe719b21fae13c7a7cf3253f970290a573e/c10/util/Logging.cpp#L104). The API was introduced to PyTorch core in https://github.com/pytorch/pytorch/pull/20698 and has been extensively [used in core](https://github.com/pytorch/pytorch/search?q=_log_api_usage_once).

> what is the reason for not just doing it in a separate file

We're interested in events like model instantiation, that's why we want to trigger the logging in model constructor. We considered adding it to model base class(#4569) but we don't have any other features to be in the base class.

> at least with a decorator

Good point, at least the logging code does not show up in the function definition.

**Comment by NicolasHug** [comment]
> [sadly, there is no category for general discussion]
> Versions
> It would also be nice to make this field not required. Often, there is no specific version. Core PyTorch also doesn't force entering version.

You can use the blank template instead:

![image](https://user-images.githubusercontent.com/1190450/142385126-bf54ed13-4555-47f7-b0e2-7c7f900a0d5f.png)

Bug reports almost always require a version, and we do this to avoid low quality or low efforts posts. Pytorch core will likely follow soon BTW.

**Comment by vadimkantorov** [comment]
Maybe it could be added by having in some file

```
func = add_logging(func)
SomeModule.__init__ = add_logging(SomeModule.__init__)
```

This way pure functional code rests clean

**Comment by NicolasHug** [comment]
I agree with you that a decorator could do the job and be less intrusive for classes and functions.

Could be a decent first issue @fmassa @datumbox ?

**Comment by fmassa** [comment]
I don't have any concerns of adding those loggings in separate files, as long as it doesn't break torchscript.

We could even keep it private to only be logged within fbcode.

**Comment by vadimkantorov** [comment]
About forcing to report versions, snippets for learning versions are not documented in core: https://github.com/pytorch/pytorch/issues/32864

**Comment by kazhang** [comment]
Using decorator to log function API usage seems to be a dead end 😩: JIT doesn't like decorator (more specifically `**kwargs`).

We can apply decorator on models/transforms/datasets but not ops/io. I'm leaning towards using two methods in torchvision: decorator and log API, until we find a better solution (or not going to support TorchScript)

**Comment by datumbox** [comment]
I agree that ideally a decorator would have been nicer, but I'm not convinced that having 2 separate implementations or sacrificing JIT scriptability is worth it. IMO the current solution is a one-liner and it's clean enough.

**Comment by kazhang** [comment]
I found a way to inspect caller's module and function name, we could further simplify the log function to be like
```
_log_api_usage_once()  # without passing the name of function e.g "torchvision.ops.nms"
```
https://stackoverflow.com/questions/1095543/get-name-of-calling-functions-module-in-python

**Comment by datumbox** [comment]
Indeed you can capture the caller without passing parameters but I think we are very likely to still get issues with JIT. Plus the performance issues you noted. 

Something that I want to make more crisp is what we try to optimize by this change. Does omitting the string in the function call make the code better or easier to read? 

I would argue that since the method call can't be removed, the lack of parameter makes little difference. Maybe passing the string makes it more clear what the logger does. I could be wrong but it feels like to resolve this issue, given our JIT constrains, is to document what the `_log_api_usage_once()` method does and provide clear details on what it captures and what it doesn't capture. The clarifications posted above sounds enough. Shall we do that on a new PR?

I'm open to more ideas on how to make the code more readable, I just thing it's hard to optimize this case by a lot as it's already a one-liner.
