### ISSUE TITLE
Bug in keypoint_rcnn initializer

### ISSUE THREAD

**Issue by JunzheJosephZhu** [pytorch/vision#5126]
### 🐛 Describe the bug

Line 1890 in keypoint_rcnn
"
        if num_classes is not None:
            if keypoint_predictor is not None:
                raise ValueError("num_classes should be None when keypoint_predictor is specified")
"
Shouldn't we change num_classes to num_keypoints in this case?

### Versions

Newest

cc @datumbox

**Comment by datumbox** [comment]
@JunzheJosephZhu You are right, this is a bug. Instead of `num_classes` we should be checking the `num_keypoints`.

The problem now is that the default value of `num_keypoints=17`, so checking for `None` makes no sense. One way to address this is to change the default value to `None` and for BC overwrite the value to 17 after the highlighted-if. Let me know if you would like to send a PR to fix this.

**Comment by themendu** [comment]
Hi @datumbox, I have created a [pull request](https://github.com/pytorch/vision/pull/5180) solving the above issue. Please review and comment on it.
