### ISSUE TITLE
Example doesnt work

### ISSUE THREAD

**Issue by mrinath123** [pytorch/vision#5163]
### 📚 The doc issue

In this example for fasterrcnn https://github.com/pytorch/vision/blob/e65a857b5487a8493bc8a80a95d64d9f049de347/torchvision/models/detection/faster_rcnn.py#L354
in the # For training part
the output is giving an error
"ValueError: All bounding boxes should have positive height and width. Found invalid box [0.45278316736221313, 0.678650438785553, 1.0717594623565674, 0.416100412607193] for target at index 0."

### Suggest a potential alternative/fix

Maybe change the way bbox are defined, here it is being initialized randomly

**Comment by datumbox** [comment]
@mrinath123 Thanks, you are right. Executing the following:

```python
import torch
import torchvision

model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
images, boxes = torch.rand(4, 3, 600, 1200), torch.rand(4, 11, 4)
labels = torch.randint(1, 91, (4, 11))
images = list(image for image in images)
targets = []
for i in range(len(images)):
    d = {}
    d['boxes'] = boxes[i]
    d['labels'] = labels[i]
    targets.append(d)
output = model(images, targets)
 # For inference
model.eval()
x = [torch.rand(3, 300, 400), torch.rand(3, 500, 400)]
predictions = model(x)
```

Leads to the above exception because some of the bottom right coordinates of the boxes have larger values than the ones of top left. As you correctly pointed out, to fix this we need to ensure that `boxes[:, :, 2:4] > boxes[:, :, 0:2]`.

We could add something like the following right after the initialization of `boxes` to fix it but other patches exist:
`boxes[:, :, 2:4] = boxes[:, :, 0:2] + boxes[:, :, 2:4]`

Let me know if you would like to send a PR to fix the problem.

**Comment by mrinath123** [comment]
I will love to send you a PR, would be my 1st contribution to this awesome framework!

**Comment by datumbox** [comment]
Sounds great! Feel free to add me as a reviewer once you send the PR. Looking forward to your contribution. :)

**Comment by mrinath123** [comment]
Hi! I tried to make a PR https://github.com/pytorch/vision/pull/5165 it's my first time contributing, if I make some mistake do tell me.
Thanks
