### ISSUE TITLE
Potential simplifications to the prototype dataset testing

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#5269]
As discussed offline with @pmeier, there are a few potential simplification / improvements we could make to the prototype datasets tests. 

- The tests currently create a tmp dir, but this tmp dir isn't cleaned up after the tests are run.
- The tests are currently designed such that the mocked dataset root is the same across all tests. Is this worth enforcing? We might be able to simplify the code if we don't.
- We currently rely on a cache, which isn't really needed in terms of speed (tests are fast enough for now). The cache leads to slightly more complicated code, in particular regarding what each dataset mock can return (a dict with datasetConfig as keys). Removing the cache might simplify the code without sacrificing too much in testing time. If the test time becomes an issue this is something we can revisit.

- qmnist test 50k is quite slow as it needs to generate a lot of images. Is it worth keeping the test? Is it worth even keeping the dataset at all? Should we think of a faster way to test it?

cc @pmeier @bjuncek

**Comment by pmeier** [comment]
> qmnist test 50k is quite slow as it needs to generate a lot of images. [...] Is it worth even keeping the dataset at all?

Yes, I see no point in removing it. What is debatable is if we want to keep the `split="test10k"` and `split="test50k"` variants. The latter is the offender for the slow tests since it needs to generate at least 50k + 1 samples.

QMNIST was generated from the same source as MNIST with the goal of having more test samples while trying to match the processing of the original MNIST data. In the [words of the authors](https://github.com/facebookresearch/qmnist):

> The QMNIST10K test uses the first 10000 QMNIST testing digits, that is, the reconstruction of the ordinary MNIST testing set. The QMNIST50K test uses the remaining 50000 QMNIST testing digits, that is, the reconstruction of the lost MNIST testing digits.

IIUC, these two splits only have some merit when you want to compare QMNIST to MNIST. If you actually train on QMNIST, I don't think someone will actually use them since the whole idea of the dataset is to provide more test samples.

Thus, I'm ok with removing these splits and thus simplify the implementation and speed up the tests.
