### ISSUE TITLE
Support `transforms` argument for ImageNet / ImageFolder / DatasetFolder

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/vision#5324]
### 🚀 The feature

Currently they seem to only support old style `transform=`, `target_transform=`. Joint transforms are needed for augmentations. I guess these datasets just need to pass in `transforms=` argument to the base `VisionDataset` class

### Motivation, pitch

N/A

cc @pmeier

**Comment by pmeier** [comment]
What joint transformation do you want to use with a classification dataset? I know there is `MixUp`, `CutMix`, and other variants, but these can only applied after some batching happened.

**Comment by vadimkantorov** [comment]
I'm augmenting it with ImageNet provided bboxes: https://github.com/pytorch/vision/issues/5318

This is useful for evaluating localization.

I'm currently just setting `.transforms` in the resulting dataset object, and it works because the base class VisionDataets indeed supports `.transforms`, but it would be better for consistency if it supported the same arguments.

**Comment by pmeier** [comment]
For `ImageNet` there is indeed a use case here. If we add support for bounding boxes, we will of course also add a `transforms` parameter. Thus, let's keep the discussion about this in #5318.

For `ImageFolder` I don't see a viable way forward to support this. The premise of these kind of datasets is that you only have the image and use its folder as category. Thus, there won't be support for any other annotations. And with that, I don't see a point of having a `transforms` parameter for them.

**Comment by vadimkantorov** [comment]
> For `ImageFolder` I don't see a viable way forward to support this.

A very easy way forward is to just add a constructor argument `transforms=` and pass it onto DatasetFolder and VisionDataset. VisionDataset already knows how to handle all these arguments. I consider it quite viable. In any case, please feel free to close this issue if introducing such consistency would actually hurt some other aspects.

> Thus, there won't be support for any other annotations. And with that, I don't see a point of having a `transforms` parameter for them.

I think consistency with other dataset classes is important. Please consider the case of deriving custom datasets from ImageFolder. Then this is helpful even regardless of whether it was a class for classification dataset or not.

**Comment by pmeier** [comment]
> A very easy way forward is to just add a constructor argument `transforms=` and pass it onto DatasetFolder and VisionDataset. VisionDataset already knows how to handle all these arguments (hmm, and also a two-line modification of DatasetFolder's getitem would be needed).

This is indeed an easy solution, but that is not what I meant with "viable". I meant "viable" in the sense that the change should make sense. See below why I think it doesn't.

> I think consistency with other dataset classes is important.

Agreed, but this is an argument against adding it. We currently only use `transforms` for detection or segmentation datasets. Since `ImageFolder` is a classification dataset, adding `transforms` would make the API more inconsistent. See for example [this](https://gist.github.com/pmeier/14756fe0501287b2974e03ab8d651c10) for an (outdated) list of the transform support of our datasets.

> Please consider the case of deriving custom datasets from ImageFolder. Then this is helpful even regardless of whether it was a class for classification dataset or not.

If you don't have classification data, subclassing from `ImageFolder` is probably not a good way to go. If you want a way to collect image files from an image folder structure, use [`torchvision.datasets.folder.make_dataset`](https://github.com/pytorch/vision/blob/8aad0e0a64c65b4e16855764288f0bc2ad2e14c0/torchvision/datasets/folder.py#L49) in a custom dataset. 

> Another usecase is easily plugging an already existing augmentation pipeline or plugging a simple dataset into an existing dataset/aug code.

That is a valid argument and we are going to solve this with the upcoming API's for datasets and transforms.

**Comment by vadimkantorov** [comment]
My point is that what is originally thought as classification dataset, can very well be cast or augmented as something else entirely by the users, library authors or anyone can't predict all valid usecases. Such inconsistencies are hurting user experience as require more custom classes that otherwise could have been implemented as a function (so force more object orientation and worse support of functional programming).
