### ISSUE TITLE
Separate autoaugment into an own library loosely coupled to torchvision

### ISSUE THREAD

**Issue by KOLANICH** [pytorch/vision#5493]
### 🚀 The feature

Separate autoaugment into an own library loosely coupled to `torchvision`.

Instead define
* a unified interface for specifying augmentations in a declarative way, covering the features of all major image augmentation libs:
    * an aug pipeline specification in form of YAML, which is to be transformed into ...
    * an aug pipeline specification in a form of python objects
    * the interfaces augmenters impls must inherit
    * the interface returning the mapping of implemented augmenter classes to the abstract interfaces
    * the class doing the augmentation using the interfaces.
* an implementation using [`kornia`](https://github.com/kornia/kornia), inheriting the interfaces.

### Motivation, pitch

Currently `autoaugment` is too tied to `pytorch` and so not very useful in scenarios not involving `pytorch` at all.

For example [it'd be nice to have a library of augmentation presets](https://github.com/open-source-ideas/ideas/issues/321), useful in scenarions where nothing but `numpy` and `PIL` is needed within dependencies. For example, my use case is perceptual hash distance thresholds calibration.

There are some libs doing that in pure numpy + imgio, like [`imgaug`](https://github.com/aleju/imgaug), but it takes some effort to adapt the code from `autoaugment.py` into the code for these libs.

So we need to specify the augmentation pipelines the way convenient for transfroming them to the "native" way used within the libs and we need the code doing the conversion automatically for us.

**Comment by datumbox** [comment]
@KOLANICH Thanks for the proposal. 

You are right to say, TorchVision is closely tied to PyTorch. This is because it is its specialization to Computer Vision. By being very closely coupled, we are able to use GPU acceleration, JIT scriptability for mobile deployment and other PyTorch features.

Though I understand your use-case is valid, decoupling TorchVision from PyTorch is not a direction we want to take. Ideally we would like to make our functional transforms good enough so that other libraries on the PyTorch ecosystem choose to use them to operate on top of Tensors so that we can get maximum performance out of them. 

I understand the above doesn't align with your use-case as you are mostly interested in converting the AutoAugment implementations to work with PIL/numpy. Perhaps if installing PyTorch is not a problem for you, you can still use our AutoAugment implementations by just converting your input to Tensors, calling AA and then convert the output back to the original format. The overhead should be small but you need to run your own checks.

I'm going to close the issue because, as I mentioned above, decoupling TorchVision from PyTorch is not something we want to do but I'm happy to discuss further if you have concerns/feedback. Again thanks for the input!

**Comment by KOLANICH** [comment]
>By being very closely coupled, we are able to use GPU acceleration

`kornia` is a GPU-accelerated library of transforms above pytorch. 
 So GPU acceleration and differentiability.

>Perhaps if installing PyTorch is not a problem for you, you can still use our AutoAugment implementations by just converting your input to Tensors, calling AA and then convert the output back to the original format. The overhead should be small but you need to run your own checks.

Yeah, I currently do this, but I think it'd be cool to have all the augmentations available in other frameworks, the full set of them. I also don't think that making pytorch mandatory is a good thing, ideally we should be able to specify augmentation pipeline once and use the predefinee pipeline in other frameworks, like TensorFlow and numpy, and maybe even being able to export it as ONNX.
