### ISSUE TITLE
Update low-level functional transforms with value_range

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#5502]
Following https://github.com/pytorch/vision/pull/5500#discussion_r816599553 we may want to update low-level functional transforms with `value_range` argument to avoid implicit hard-coded max range definition:
- 255 for uint8
- 1.0 for float

Today this is done for 
- adjust_hue
https://github.com/pytorch/vision/blob/95d418970e6dbf2e4d928a204c4e620da7bccdc0/torchvision/transforms/functional_tensor.py#L210-L211

- all ops using `_blend`:
https://github.com/pytorch/vision/blob/95d418970e6dbf2e4d928a204c4e620da7bccdc0/torchvision/transforms/functional_tensor.py#L259-L262

We can introduce new argument `value_range` and use it explicitly for these ops.
In general we can think of `value_range` as a tuple (min, max) which would cover majority of imagery where channels ranges are similar. There could be however other type of images (e.g. think of non-RGB color spaces or particular imagery) where value ranges could vary per channel, thus we may need to represent `value_range` as a list of 2-tuples: [(min_1, max_1), (min_2, max_2), ...] 

cc @bjuncek @datumbox

**Comment by datumbox** [comment]
I agree with the idea of passing `value_range` on our existing kernels. When `None` we can estimate the `bound` using our existing approach.

Concerning using single values vs single MinMax vs Multi MinMax, I think all boils down to what is our target. Do we see TorchVision offering native support for Transforms for more exotic non-RGB/Grayscale spaces? Perhaps that could be useful for medical or astronomical applications but we should be careful not to overcomplicate the API with features we won't use. Are transforms that use `_blend` even likely to be used in such domains?

I would like to get the advise of you and @pmeier on this one for how we proceed.

**Comment by NicolasHug** [comment]
Apart from making the implicit ranges more explicit, what are other problems that having `value_range`  would address?

I agree that the way we currently handle ranges isn't nice (read: not documented enough). But from my non-informed POV, it looks like adding `value_range` would add a lot of extra complexity for something that might be solved with better docs / user awareness?

**Comment by datumbox** [comment]
@NicolasHug Thanks for the feedback, I think we have a description/context gap on this issue. Instead of jumping directly to the problem, we should provide info on what we try to solve and why.

The current API uses ToTensor and PILToTensor to not only convert the image to Tensor but also scale it to [0,1]. This is somehow problematic because the ToTensor does too many things. As a result of this implicit scaling, the low-level kernels try to guess the max pixel value of the image from its type. 

Though we will maintain this guessing for BC, providing a `range_value` to the low-level kernels can free us from using ToTensor. In fact we can just maintain the image in its original space whatever it is and not have to normalize it until the very end when it's thrown to the model. This will make the pictures easier to visualize and combine. It will also remove the need for calling methods like ToTensor, ConvertImageDtype etc.

**Comment by vfdev-5** [comment]
no, neither `torch.iinfo` nor `torch.finfo` is scriptable, https://github.com/pytorch/pytorch/issues/41492

**Comment by datumbox** [comment]
@vfdev-5 Thanks for checking. Is it possible to simplify the `_max_value()` ? Is there are reason why we don't have these pre-estimated and stored in mapping for all the supported types?

**Comment by vfdev-5** [comment]
I think the reason is that torch script does not support global. We could do however something like:
```python

def convert_image_dtype(image: torch.Tensor, dtype: torch.dtype = torch.float) -> torch.Tensor:

    # ...
    _max_values: Dict[torch.dtype, int] = {
        torch.uint8: 256,
        torch.int8: 127,
        torch.int16: int(2 ** 15),
        torch.int32: int(2 ** 31),
        torch.int64: int(2 ** 63),
        ...
    }

    input_max = _max_values[image.dtype]
```

@datumbox do you think it worth a change ?

**Comment by datumbox** [comment]
I think that makes sense. There is typo on the first record for `torch.uint8`, it should be `255` right?

**Comment by pmeier** [comment]
For the integer types, there is a `-1` missing:

```py
>>> assert torch.iinfo(torch.int16).max == 2**15 - 1
```

**Comment by datumbox** [comment]
I think we should close this for now.
