### ISSUE TITLE
module 'torchvision.models' has no attribute 'to'

### ISSUE THREAD

**Issue by manza-ari** [pytorch/vision#5591]
### 🐛 Describe the bug

module 'torchvision.models' has no attribute 'to'

I am trying to implement data-parallel but this is my error.

models = torch.nn.DataParallel(models)
  File "/home/kanza/anaconda3/envs/withgpus/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 145, in __init__
    self.module.to(self.src_device_obj)
AttributeError: module 'torchvision.models' has no attribute 'to'

### Versions

My versions for Ubuntu 16, and Pytorch are following:
torch version: 1.7.1
torchvision version: 0.8.0a0

**Comment by NicolasHug** [comment]
Hi @manza-ari , it's fairly difficult to help since most of the code is missing. But judging by the error message and the code, it looks like you passed `torchvision.models` to `torch.nn.DataParallel`. That cannot possibly work, `torchvision.models` is a module, not a specific model.

You might be interested in this tutorial for how to use the DataLoader: https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html

Since this is a user question more than a bug report, I'll close the issue. If you believe this is a legit bug in torchvision, please feel free to re-open the issue.

**Comment by manza-ari** [comment]
Can you please help where to add exactly data_parallel? I am little confused about the following code 
https://github.com/razvancaramalau/Sequential-GCN-for-Active-Learning/blob/master/main.py

I have added here whereas CUDA_VISIBLE_DEVICES is set as 0 
`
with torch.cuda.device(CUDA_VISIBLE_DEVICES):
                    if args.dataset == "fashionmnist":
                        resnet18    = resnet.ResNet18fm(num_classes=NO_CLASSES).cuda()
                    else:
                        #resnet18    = vgg11().cuda() 
                        resnet18    = resnet.ResNet18(num_classes=NO_CLASSES).cuda()
                    if method == 'lloss':
                        #loss_module = LossNet(feature_sizes=[16,8,4,2], num_channels=[128,128,256,512]).cuda$
                        loss_module = LossNet().cuda()

                models      = {'backbone': resnet18}
                if method =='lloss':
                    models = {'backbone': resnet18, 'module': loss_module}

                # Data Parallel                      
                models = torch.nn.DataParallel(models, device_ids=[0,1,2,3])

                torch.backends.cudnn.benchmark = True


`
