### ISSUE TITLE
ImageFolder Image mode.

### ISSUE THREAD

**Issue by ryanpeach** [pytorch/vision#561]
`ImageFolder`'s `pil_loader` converts to RGB. This may be a standard for images, but I recently needed RGBA and was confused as to why it wasn't opening correctly (its not in the documentation that it does this, and there isnt an argument that makes it obvious or allows you to overwrite this behavior, you need to make your own loader). I propose we add an option to `ImageFolder` called `image_mode`, defaulted to "RGB", such that if this parameter is any value other than none that value is passed to `pil_loader`'s convert call, and if it is `None` it bypasses the convert function altogether.

**Comment by fmassa** [comment]
I'd say that it's fairly easy to write a new loader, and also more generic, because this format conversion is specific to PIL.

We can improve the documentation of the `loader` to make it explicit that it users PIL and converts the image to 'RGB' format, but I don't think it's necessary to pass yet another argument to the constructor of the `ImageFolder`.

For reference, here is how I'd write a loader to always convert to `RGBA` format:
```python
def pil_loader_rgba(path):
    # open path as file to avoid ResourceWarning (https://github.com/python-pillow/Pillow/issues/835)
    with open(path, 'rb') as f:
        img = Image.open(f)
        return img.convert('RGBA')
```

**Comment by ryanpeach** [comment]
True it's a small change. I can understand the rationale since no other torchvision transform takes RGBA. Let's just explicitly mention it in the Documentation then.

**Comment by fmassa** [comment]
Could you send a PR to improve the docs?
