### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED when trying to download EMNIST from torchvision. 

### ISSUE THREAD

**Issue by GanyuWang** [pytorch/vision#5681]
### 🐛 Describe the bug

2022/3/23 around 10 pm. 

I am trying to download the EMNIST using torch vision. Certificate expired. 

training_set = torchvision.datasets.EMNIST('./data', split="byclass", train=True, download=True)

The error raise. 
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)>

### Versions

[pip3] numpy==1.21.5
[pip3] torch==1.10.0+cu111
[pip3] torchaudio==0.10.0+cu111
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.11.0
[pip3] torchvision==0.11.1+cu111

**Comment by dogeplusplus** [comment]
I have just tried this now and had no issues downloading. I also had SSL certificate errors in the past week when downloading datasets and I believe this to be not related to pytorch but with the certificates that come with Python (or the lack of). You can verify this by trying to similarly download datasets using `tensorflow_datasets`, or doing a HTTPS request with `requests`/ `urllib`. Depending on your operating system your solution may be different:

Similar:
- Linux: https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error
- MacOS: https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

Since I use Ubuntu my solution was a combination of installing `ca-certificates`, `certifi` pip library, and doing this https://stackoverflow.com/a/58394602 . But your problem may be different.

**Comment by GanyuWang** [comment]
The torch team fixed this issue several days later.
