### ISSUE TITLE
Code to convert model weights from facebookresearch/ConvNeXt

### ISSUE THREAD

**Issue by tstandley** [pytorch/vision#5682]
### 🚀 The feature

Can you share the code used to convert model weights from the original author's convnext code to the torchvision version? 

### Motivation, pitch

I guess this isn't actually a request to modify torchvision, but I assume code was used to convert model weights from facebookresearch/ConvNeXt to the torchvision verstion. Can I get access to this code somehow? I have some weights that I painstakingly trained using the FB version of convnext that I'd like to use with torchvision.

Thanks!

**Comment by datumbox** [comment]
@tstandley thanks for the request.

We did not concert the weights from `facebookresearch/ConvNeXt`. We trained the models from scratch using our [new recipe](https://pytorch.org/blog/how-to-train-state-of-the-art-models-using-torchvision-latest-primitives/) and that's why the accuracies offered by TorchVision are higher than the original paper. 

Still I believe you should be able to convert the weights easily by zipping together the keys of the other implementation with the keys of TV and remapping the values. I'm going to close this to keep things tidy, but if you have any questions please let us know.
