### ISSUE TITLE
Add tests for `sigmoid_focal_loss` and `generalized_box_iou_loss`

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#5688]
### 🚀 The feature

The `sigmoid_focal_loss` and `generalized_box_iou_loss` ops are not currently tested. We should create the necessary unit-tests that check the validity for multiple input types.

**Comment by oke-aditya** [comment]
This will also help folks working on Ciou ad Diou loss. @YosuaMichael I can work on this if you like :) 

Reference tests fvcore
https://github.com/facebookresearch/fvcore/blob/main/tests/test_giou_loss.py

**Comment by yassineAlouini** [comment]
Thanks @oke-aditya for the link.

**Comment by YosuaMichael** [comment]
Hi @oke-aditya thanks for the offer! Is there anything urgent that need this test?

Currently I actually do this task for the sake of learning (since I am new and it would be good to touch as many part of the code as possible), hence I would like to do this issues myself if possible, however it would take more times.

**Comment by YosuaMichael** [comment]
This issue is done with #5783 and #5792
