### ISSUE TITLE
remove inplace 

### ISSUE THREAD

**Issue by jgerlach93** [pytorch/vision#5703]
https://github.com/pytorch/vision/blob/aa21197462591a89f527ded3938ffe62f7d8cb8f/torchvision/models/resnet.py#L81

the inplace = True is not actually needed, is it?  

i dont really see self.relu being used as inplace anywhere; rather x = self.relu(x), everywhere.

**Comment by datumbox** [comment]
This has to do with how the operation is performed and whether the returned x is a new block of memory or not. The code as-is, applies the relu operation on the same x value instead of copying it. So it does work.

I'm going to close this issue as I believe I've answered your question. If you have more comments, feel free to reopen.
