### ISSUE TITLE
over padding in RandomCrop when pad_if_needed 

### ISSUE THREAD

**Issue by YHRen** [pytorch/vision#576]
in random_crop, pad_if_needed, this seems over padded the image with 2* delta_w 

https://github.com/pytorch/vision/blob/fe973ceed96da733ec0ae61c525b2f886ccfba21/torchvision/transforms/transforms.py#L448

**Comment by fmassa** [comment]
This has been recently merged in https://github.com/pytorch/vision/pull/564

The logic is that if the original image is smaller than the requested crop size, there are multiple possible ways of filling it with the padding value so that the full original image is inside the crop.

By adding such padding value, we guarantee that the whole image will be inside the crop, but we give the possibility of random crops, which effectively acts as data augmentation.

I'm closing the issue, but let me know if you disagree with this reasoning.

**Comment by YHRen** [comment]
Hi Frank,

I see. Thank you for the explanation.
Now I understand.

Bests,
Ray
