### ISSUE TITLE
Deeplabv3 model builders accept unused **kwargs parameter.

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#5883]
Not sure if this is by design or a minor bug, but the deeplabV3 model builders accept a `**kwargs`  parameter and do not use it.

https://github.com/pytorch/vision/blob/d425f007782051ab08e9c0fbfe06b072313f4649/torchvision/models/segmentation/deeplabv3.py#L222:L222

@datumbox should we remove these?

**Comment by datumbox** [comment]
I believe this is done across all model builders and kept there for consistency (all other builders do it). For example `lraspp_mobilenet_v3_large` makes use of it to handle extra params coming from our reference scripts [pass parameters](https://github.com/pytorch/vision/blob/main/references/segmentation/train.py#L135).

**Comment by datumbox** [comment]
Good question. Obviously here the only argument for keeping it is to be consistent with the other model builders.

Every other model builder supports is because it redirects the params to the model class. In segmentation we dont do it because the model classes don't receive too many extra parameters.

I see 2 options:
1. Go for consistency. Leave the kwargs be but also pass them on the segmentation model classes. 
2. Remove them as they are unnecessary for deeplabv3.

Both have cons. For example in (1) will lead to putting unnecessary `kwargs` params in the model classes while in (2) one can argue that removing it is not BC.

Frankly I don't have a strong opinion over that. Happy to go with whatever you decide.

**Comment by pmeier** [comment]
Cross linking https://github.com/pytorch/vision/pull/5001#discussion_r763326832 since we had this discussion before.
