### ISSUE TITLE
transform.Normalize floating point error for uniform images

### ISSUE THREAD

**Issue by swigicat** [pytorch/vision#589]
If a uniform image (e.g. all zeros, from a faulty loading operation) is fed to the normalize transform, the program will just output a "Floating point error (core dumped)" message with no debug trace. It would be nice that the standard deviation is checked against zero before attempting to divide by it, would save many debugging hours...

**Comment by vishwakftw** [comment]
Could you please provide a code-example?

**Comment by fmassa** [comment]
This happens only if your image is in an integer type. Cast your torch tensor to `.float()` and this segmentation fault will not happen. Also, dividing integer-valued images by its variance is generally not a good idea, as you lose a lot of information due to rounding.

There is not much we can do in torchvision about this, and I'm not sure that this will be fixed anytime soon in PyTorch either.
