### ISSUE TITLE
Imagenet 10 or Imagenette

### ISSUE THREAD

**Issue by t-vi** [pytorch/vision#5892]
### 🚀 The feature

I think it would be cool to have a readily-downloading dataset of 10 categories and imagenet shape (i.e. to be fed into 224x224). Currently the closes is likely STL10, but I think one of Imagenet-10 ( https://paperswithcode.com/sota/image-clustering-on-imagenet-10 ) or Imagenette ( https://github.com/fastai/imagenette ) might be worthwhile to add.

### Motivation, pitch

With vision transformers, it seems even more interesting to get a reasonably-sized dataset with images of similar type (size) of ImageNet.

### Alternatives

Manually downloading (torch.hub.download?), extracting and using ImageFolder.

cc @pmeier @YosuaMichael

**Comment by datumbox** [comment]
@t-vi Thanks for the suggestion.

I think that's reasonable. Another option could be [Tiny Imagenet](https://paperswithcode.com/dataset/tiny-imagenet). Worth exploring as an addition on the new Datasets API.

**Comment by t-vi** [comment]
Note that tiny imagenet is 64x64 , I was hoping to have a smallish dataset with usual imagenet sizes.

**Comment by pmeier** [comment]
Is "ImageNet10" available as independent dataset? paperswithcode.com has it listed in the clustering benchmark as you listed, but it is not listed in their dataset section. Is it just a subset of the original ImageNet dataset?

As for "imagenette" we could easily provide that. I'll add it to my backlog when the new dataset API is final.

**Comment by t-vi** [comment]
I think it is a subset of imagenet. I don't remember which was the first paper that I saw used it, but e.g. here is the list of classes:
https://github.com/Yunfan-Li/Contrastive-Clustering/tree/main/datasets

**Comment by pmeier** [comment]
> I think it is a subset of imagenet.

Is that the same for imagenette? From looking at the file structure that seems to be the case. If so I'm a little confused how they can provide public download links whereas the regular imagenet doesn't do that due to licensing issues.

In case they are actually subsets, I wouldn't put much priority on adding them to our API for now. With the new datasets (available under `torchvision.prototype.datasets` in the nightly releases), we can easily achieve this with

```py
import functools

from torchvision.prototype import datasets, features


def filter_wnid(sample, *, wnids):
    return sample["wnid"] in wnids


def fix_label(sample, *, wnids, categories):
    sample["label"] = features.Label(wnids.index(sample["wnid"]), categories=categories)
    return sample


def load_imagenet_subset(*wnids):
    info = datasets.info("imagenet")
    wnids_to_categories = dict(zip(info["wnids"], info["categories"]))
    categories = [wnids_to_categories[wnid] for wnid in wnids]

    return (
        datasets.load("imagenet")
        .filter(functools.partial(filter_wnid, wnids=wnids))
        .map(functools.partial(fix_label, wnids=wnids, categories=categories))
    )


imagenet_10 = load_imagenet_subset(
    "n02056570",
    "n02085936",
    "n02128757",
    "n02690373",
    "n02692877",
    "n03095699",
    "n04254680",
    "n04285008",
    "n04467665",
    "n07747607",
)

for sample in imagenet_10:
    print(sample["wnid"])
    print(sample["label"])
    print(sample["label"].to_categories())
    break
```

```
n02056570
Label(0)
king penguin
```

It is not really efficient since we still are going to load (not decode!) all other images and throw them away, but it should be sufficient for prototyping.

**Comment by pmeier** [comment]
> I have no insight into it, except that maybe the difference of giving it out to your buddies or giving it out to everyone might not be that big in terms of copyright.
> 
> My key interest would be to not have to manually code downloading the thing. Alternatively, maybe having a dataset that does the downloading of a given URL + checksum would also work for me, if the link to imagenette is that scary.

I don't think it has any implications for us if we provide a wrapper around a publicly available URL. In case the usage was not authorized, the people that published it will be at fault. Since the repository is licensed under [Apache License 2.0](https://github.com/fastai/imagenette/blob/master/LICENSE), I think it is fair to assume for us and our users that the data is fine to use under this license. There is nothing in the README that would contradict this.

My reason for bringing this up was that we should be extra careful when checking if imagenette is actually a subset of imagenet, since the images for the latter are not publicly available and thus I find it odd that the others are.

@yassineAlouini Could you also put this in the "new datasets lists" that you are compiling?

**Comment by datumbox** [comment]
> I don't think it has any implications for us if we provide a wrapper around a publicly available URL.

I am not too sure about this. I'm not an expert to copyrighting so before starting any work on this we would have to ask advice of people within Meta who have this expertise. It's OK to record this as a request from the community, just make sure to ping me prior kicking off work on it so that I can try to clarify these points. This will help us avoid throwaway work.

**Comment by leopck** [comment]
@datumbox @pmeier @yassineAlouini @t-vi I would like to open up this issue once again as my organization has interest in this dataset as well to be readily available, what is the current status surrounding this dataset to be in Torchvision dataset? From my understanding of their license in their repo, it shows Apache 2.0 which should be fine but would like to check if this is a showstopper for Meta or anything else. If this is not a showstopper, could we proceed in creating a PR for upstreaming Dataset with Imagenette capability into torchvision?
