### ISSUE TITLE
CU115 nightly torchvision 0.13.0 for Linux stopped updating since 20220422

### ISSUE THREAD

**Issue by xiaoyu-work** [pytorch/vision#5947]
### 🐛 Describe the bug

CU115 nightly torchvision 0.13.0 for Linux stopped updating since 20220422

Can we have an update for torchvision 0.13.0 for Linux cu115? https://download.pytorch.org/whl/nightly/cu115/torch_nightly.html

Thanks

### Versions

cuda==11.5
torchvision==0.13.0.dev

**Comment by pmeier** [comment]
They stopped after #5862. We now only provide binaries compiled against

https://github.com/pytorch/vision/blob/62740807c18e68bb0acd85895dca527f9a655bd5/.circleci/regenerate.py#L35-L37

The same is true for [PyTorch core](https://github.com/pytorch/pytorch/blob/ad8386c1320c3abddaf6cbdd580866de1720a735/.github/scripts/generate_binary_build_matrix.py#L16-L19). The latest nightly release build against CUDA 11.5 is from 20220423.

**Comment by drzraf** [comment]
Do you mind reconsidering the removal of the Linux on Cuda 11.5 ?

Cuda 11.5 is the default on Ubuntu 22.04 LTS and having a torch/torch2/torchvision build would come **very** handy.

**Comment by pmeier** [comment]
> Do you mind reconsidering the removal of the Linux 11.5 build ?

Nope. We just recently also removed CUDA 11.6 builds and are not going back. 

> Cuda 11.5 is the default on Ubuntu 22.04 LTS and having a torch/torch2/torchvision build would come very handy.

There is probably a misunderstanding here: you don't need CUDA installed to utilize a GPU from PyTorch. You only need the Nvidia driver. You only need CUDA installed if you want to build from source.

As for the Nvidia driver version, you can refer to Table 2 in https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html. For CUDA 11.5 (as for most 11.X versions) you only need version >=450.80.02. I don't know what the version of driver in the official Ubuntu repos is, but it should suffice for CUDA 11.5, given that the required driver version is quite old.

To find out what driver version you have, run `nvidia-smi` and look at the table header. This conveniently also displays the _maximum_ CUDA version that is supported. Everything below that is supported as well.

In case you install from `pip`, I recommend [`light-the-torch`](https://github.com/pmeier/light-the-torch) (note that I'm the author), since that takes care of all the stuff and simply gives you a compatible PyTorch / TorchVision / ... version for your system.
