### ISSUE TITLE
MacOS unittest and binary jobs failing

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#6070]
Both with a segfault in torchvision's `setup.py`:

- https://app.circleci.com/pipelines/github/pytorch/vision/17824/workflows/63ed118f-e479-47e5-91c1-2f0805ce2e5a/jobs/1443411

- https://app.circleci.com/pipelines/github/pytorch/vision/17824/workflows/97a4d0cf-ecd8-402f-bb8d-301cd68c2ea3/jobs/1443375

**Comment by pmeier** [comment]
Probably related to https://github.com/pytorch/pytorch/pull/77662#issuecomment-1129970086.

**Comment by albanD** [comment]
This is not an expected change. We will revert this change in core.

**Comment by pmeier** [comment]
Was fixed in pytorch/pytorch#78136! Thanks @malfet

- https://github.com/pytorch/vision/runs/6572753695
- https://app.circleci.com/pipelines/github/pytorch/vision/17866/workflows/15a8ff89-782a-40a9-8f14-34cc9cb0072b/jobs/1446630
- https://app.circleci.com/pipelines/github/pytorch/vision/17866/workflows/49b2a6cf-c54e-4c21-8a0d-a477e70c884f/jobs/1446653
