### ISSUE TITLE
ResNet with InstanceNorm and zero_init_residual

### ISSUE THREAD

**Issue by FloCF** [pytorch/vision#6074]
### 🐛 Describe the bug

Since `nn.InstanceNorm2d` has `affine=False` as default, `ResNet` can not be used with `zero_init_residual=True` and `norm_layer = nn.InstanceNorm2d`.

```python
import torch.nn as nn

from torchvision.models import ResNet
from torchvision.models.resnet import BasicBlock


ResNet(BasicBlock, [2,2,2,2], norm_layer=nn.InstanceNorm2d, zero_init_residual=True)
```
Two possible solutions:
1. Throw out an error, as the combination of `norm_layer = nn.InstanceNorm2d` and `zero_init_residual=True` simply should not be used (not sure if that is the case).
2. Call `norm_layer` with `affine=True` (and then probably also `track_running_stats=True`) in the `BasicBlock` and `Bottleneck`.

### Versions

OS: Ubuntu 20.04.4 LTS (x86_64)
Python version: 3.9.5
torch version: 1.10.2
torchvision version: 0.11.3

cc @datumbox

**Comment by YosuaMichael** [comment]
Thanks for the report @FloCF !
I have confirmed the problem, and I notice the problem is during weight initialization of the norm_layer: https://github.com/pytorch/vision/blob/main/torchvision/models/resnet.py#L223
```
nn.init.constant_(m.bn2.weight, 0)
```
In this case, if `m.bn2` is `nn.InstanceNorm2d` then it will not have any weight, or in other word `m.bn2.weight` is None and hence it cause error.

I tried to create a bugfix here: https://github.com/pytorch/vision/pull/6082 but I may not have a full context, so lets wait until it is reviewed.
