### ISSUE TITLE
[v0.13.1] Bugfix Release Tracker

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#6300]
Same as https://github.com/pytorch/vision/issues/6081 but for 0.13.1.

**Comment by NicolasHug** [comment]
Category: binary fix

main PR: https://github.com/pytorch/vision/pull/6298
release branch PR: TODO

**Comment by NicolasHug** [comment]
Category: FX fix

main PR: https://github.com/pytorch/pytorch/issues/81118
release branch PR: TODO

Ref: https://github.com/pytorch/pytorch/issues/81118

**Comment by NicolasHug** [comment]
Category: minor doc improvement

main PR: https://github.com/pytorch/vision/pull/6314
release branch PR: https://github.com/pytorch/vision/pull/6318

**Comment by oke-aditya** [comment]
@datumbox @NicolasHug should we include #6338 in this?

**Comment by datumbox** [comment]
Good call @oke-aditya. Thanks for raising this. It would be great to fix this as this is a bug. The problem is it's not yet merged (ping Francisco to have also a look cause I made a modification on the PR). The cherrypick will be slightly tricky because we can't get the improvements on tests.

@NicolasHug do you know when is the absolute last moment that the Release Engineering team would allow us to bring a cherry? I'm happy to prepare such a PR if that's possible and we got time. cc @atalman

**Comment by NicolasHug** [comment]
The bugfix release is planned for today or tomorrow, so it might be too late. But I'll let Andrey confirm.

**Comment by datumbox** [comment]
Category: bugfix

main PR: #6338
release branch PR: #6343

**Comment by oke-aditya** [comment]
Race against time won by @datumbox
