### ISSUE TITLE
Installing the correct torchvision for Jetson Xavier NX

### ISSUE THREAD

**Issue by Zephyr69** [pytorch/vision#6452]
Platform: Jetson Xavier NX w/ Jetpack 4.6.1
Python: 3.6.9
------------------------------------------------------
I was following [this](https://docs.nvidia.com/deeplearning/frameworks/install-pytorch-jetson-platform/index.html) to install pytorch on NX but ran into a weird situation. The guide points to the only pytorch version available for Jetpack 4.6.1, [1.11 cp36](https://developer.download.nvidia.cn/compute/redist/jp/v461/pytorch/), yet its corresponding torchvision is 0.12.0 which cannot be installed on python 3.6.9.

How can I install the correct torchvision in this situation? Or how can I configure the correct pytorch with gpu support at all?

**Comment by pmeier** [comment]
Starting with `torch==1.11` / `torchvision==0.12` we phased out support for Python 3.6. The exact version you linked is `torch-1.11.0a0+17540c5`. That is a development build which points to pytorch/pytorch@17540c5c80f5c6cd4e0fee42ec47d881e46f47f9. It was cut somewhere between `torch==1.10` and `torch==1.11`. There is no corresponding `torchvision` version for that. 

The only option I currently see, is to bisect between `torchvision==0.11.3` and `torchvision==0.12.0` to find the first commit that doesn't support Python 3.6 and build its parent from source. Of course you can also ask NVIDIA to do that and provide the wheel for everyone.

Otherwise, you might also get away with installing `torchvision==0.11.3` as a CPU only build. For the most part we use `torch` ops instead of custom ones. In all these cases you will have access to all features that the installed `torch` version gives you. 

```
pip install numpy pillow torchvision==0.11.3 --extra-index-url https://download.pytorch.org/whl/cpu
``` 

However, there are no guaranties for the compatibility between these versions.
