### ISSUE TITLE
[Documentation] Class and function signatures in the documentation not pleasant to eyes 

### ISSUE THREAD

**Issue by abhi-glitchhg** [pytorch/vision#6975]
### 📚 The doc issue

Hello! 

This isnt a major issue imo, and maybe related to sphinx than torchvision. Opening here to get some inputs from you all. :)

I was going through the [transforms](https://pytorch.org/vision/stable/transforms.html) documentation and i couldn't keep my eyes away from the strange descriptions of the parameters.  In some rows, `root` parameter was out of the list(`[ ]`) and also `,` at the begining of the list in many rows.  Few rows did not have any list  at all.
 
 
![Screenshot 2022-11-24 221046](https://user-images.githubusercontent.com/72816663/203833828-1e836ede-98bd-4c9b-b2e1-9e4f0912f25d.png)

This is case for other summary pages as well.

![Screenshot 2022-11-24 221123](https://user-images.githubusercontent.com/72816663/203834088-63a7eb20-cc4d-4620-b8fe-6d8ac93c9173.png)

### Suggest a potential alternative/fix

After spending some time i noticed that the list is getting created for the parameters which have a default value. If some function/class doesn't have any default value in its defination/constructor, no list is created. 

i think the problem could be solved in 2 ways,
1) Currently for the parameters having a default value, a list is created. Write a regex function which would remove the `[ ` and `]` from `param1[, param2, param3]` . But I'm not sure if this is practically feasible or not.
2) Remove the arguments/parameters [i believe function/class signature would be the proper term here] from the summary pages. I was able to do this for the remove the function signatures  with [:nosignatures: ](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#directive-autosummary) directive in .. autosummary. 

But we cant do this for class signatures. :( 

Here's how 2nd option would look like.

![image](https://user-images.githubusercontent.com/72816663/203839974-b3e06fb4-ae20-42be-a680-c6051f9b1ccc.png)

![image](https://user-images.githubusercontent.com/72816663/203840013-811c2d57-a107-4df8-9a28-86e67bd6e536.png)

cc: @NicolasHug , @datumbox

**Comment by pmeier** [comment]
> After spending some time i noticed that the list is getting created for the parameters which have a default value. If some function/class doesn't have any default value in its defination/constructor, no list is created.

AFAIK, this is default notation for wrapped C functionality. The official Python documentation shows the same behavior, e.g. for [`range`](https://docs.python.org/3/library/stdtypes.html#range). However, our functions are proper Python functions and thus we could have the proper annotation there. This is also done in the Python docs, e.g. [`str.encode`](https://docs.python.org/3/library/stdtypes.html#str.encode). 

> In some rows, `root` parameter was out of the list(`[ ]`) and also `,` at the begining of the list in many rows. Few rows did not have any list at all.

`root` is always outside of the brackets, since it is never optional. It is only missing for `FakeData` since that doesn't have a root.

> I was going through the [transforms](https://pytorch.org/vision/stable/transforms.html) documentation and i couldn't keep my eyes away from the strange descriptions of the parameters.

I think that is subjective. If one understands the notation, I think it is quite a nice way to have a glance at the signature. I often know the operator I want to use, but forgot the exact syntax. 90% of the time, I can get it from the summary. As such I would put it up for discussion if this is something we want.

**Comment by abhi-glitchhg** [comment]
>AFAIK, this is default notation for wrapped C functionality

Oh I was under impression that this is not a style but a mistake. I understand it now. Thanks @pmeier  and  apologies.
