### ISSUE TITLE
Trying to build torchvision 0.13.0 from source to run YOLOv5 natively on Jetson nX

### ISSUE THREAD

**Issue by aatishkr** [pytorch/vision#7075]
Trying to build torchvision==0.13.0 from source to run YOLOv5 natively on Jetson nX

when I run pyrhon3 setup.py install is throws follwoing error
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

I had installed torch 1.12.0 from a python wheel file downloaded from jetsonzoo
https://developer.download.nvidia.com/compute/redist/jp/v50/pytorch/torch-1.12.0a0+2c916ef.nv22.3-cp38-cp38-linux_aarch64.whl

Please help

**Comment by pmeier** [comment]
> I had installed torch 1.12.0 from a python wheel file downloaded from jetsonzoo

That seems to have not worked out. Try `python -c 'import torch'`. As long as this fails, `torch` is not correctly installed and in turn `torchvision` cannot be build from source.

**Comment by aatishkr** [comment]
Can you please elaborate
I am running python3 setup.py install 
where should I use -c?

**Comment by pmeier** [comment]
You need to make sure that `torch` is correctly installed before you try to install `torchvision`. And the error you are getting states that this is not the case.

I'm going to close this issue, since this seems like an issue with your environment rather than `torchvision`. For questions please use [user forum](https://discuss.pytorch.org/). Feel free to re-open this or open a new issue if you are experiencing issues after the environment is sorted out.
