### ISSUE TITLE
Incorrect naming in layers of resnet

### ISSUE THREAD

**Issue by Spandan-Madan** [pytorch/vision#729]
In the resnet block, the downsample conv layer is not really the one doing downsampling. It's the conv1 doing the downsampling. Not sure if it can be corrected, but at least a comment can be added maybe?

**Comment by fmassa** [comment]
Hi,

Thanks for the heads up. Yes, that's true that it does not always perform a downsample, but only in the first group of a block. That's why we have renamed it `identity` instead of `residual` in https://github.com/pytorch/vision/pull/679

I'm afraid renaming `downsampling` would be a too big breaking change, but a comment explaining it would be great!

**Comment by Spandan-Madan** [comment]
@fmassa Agreed, renaming would break a lot of code. Adding comment makes a lot of sense. Should I add a comment and create a PR? Or would this be handled by the pytorch team internally?

Best,
Spandan

**Comment by fmassa** [comment]
@Spandan-Madan sure, you can send a PR adding the comments, it would be great, thanks!

**Comment by ekagra-ranjan** [comment]
Can be closed via #794

**Comment by soumith** [comment]
closed via #794

**Comment by Dirtybluer** [comment]
@fmassa Sorry to bring it up after this issue is closed.
I also find the name "**downsample**" a bit confusing and misleading. I think it'd probably be better to name it as "**project**" according to descriptions below in Kaiming He's original paper:

> we can perform a **linear projection** Ws by the shortcut connections to match the dimensions

And I can't tell why it would be a big breaking change. Shouldn't it be as easy as refactor all "downsample" as "project"? Maybe I miss some key point since I'm a newbie in PyTorch. In that case I hope you'd be kind enough to point it out for me, thx :)

**Comment by fmassa** [comment]
@Dirtybluer renaming the variables wouldn't be a big change, but imagine that a user was getting the output of the `downsample` layer as follows:
```python
out = model.layer1[0].downsample(x)
```
now this code stops working, and any other checkpoints that all the users have saved based on top of torchvision resnet will also stop working, which constitutes a BC-breaking change.

Given how often resnet is used, and how disruptive it would be to make this change, I think it's better to keep things as is.

**Comment by Dirtybluer** [comment]
@fmassa Rather clear explanations, thx!
