### ISSUE TITLE
References classification: option to save metrics 

### ISSUE THREAD

**Issue by alanjeffares** [pytorch/vision#7749]
### 🚀 The feature

In `vision.references.classification.train.py` it appears that metrics (e.g. training top 1, validation top 1) are only printed to the terminal rather than saved for future reference. I propose to save (at least optionally) epoch metrics every epoch to the `output_dir' to a file that is appended each time. 

### Motivation, pitch

This would seem like an essential feature in order to make this script usable for research (unless I am missing an alternative way of accessing these metrics).

**Comment by NicolasHug** [comment]
Hi @alanjeffares , you should just be able to redirect stdout from your shell into a file? Maybe with `tee`?


(We typically run those training scripts with SLURM / submitit / [this helper](https://github.com/facebookresearch/deit/blob/main/run_with_submitit.py) and stdout is saved in the output dir for each GPU, althoug admitedly I haven't checked *who* is responsible for that)

**Comment by alanjeffares** [comment]
Hi @NicolasHug, thanks for the response. I see, I was hoping there might be a straightforward way of storing metrics of interest in a convenient format (e.g. json) when running simple workflows through the command line. But maybe this scipt isn't designed for this sort of thing so I will write my own solution. Thanks :)

**Comment by NicolasHug** [comment]
Yeah, we don't really have a strong need for that so we haven't implemented it. We also don't want to be opinionated on how it should be done, because each user will have their own preference. But I understand this is useful in general. I think it should be fairly straightfowrad to implement for you by interfacing with out MetricLogger: https://github.com/pytorch/vision/blob/main/references/classification/utils.py#L135
