### ISSUE TITLE
Results do not correspond to current coco set

### ISSUE THREAD

**Issue by golnaz-hs** [pytorch/vision#7890]
### 🐛 Describe the bug

Hi,

I wanted to reach out and report an error that I have encountered while working on this tutorial [https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html] using my own dataset. I had successfully run the tutorial multiple times before, but unfortunately, I have been facing the following error consistently for the past three days. I've double-checked my dataset, made sure it's compatible, and reviewed the code, but this error persists.

I kindly request your assistance in resolving this issue. Your guidance and support would be greatly appreciated.

Best regards,

### Versions

AssertionError                            Traceback (most recent call last)
[<ipython-input-36-6a561c13f871>](https://localhost:8080/#) in <cell line: 4>()
     10     # scheduler.step()
     11     # evaluate(model, valid_dl, device=device)
---> 12     evaluate(model, valid_dl, device=device, epoch=epoch)
     13 
     14     checkpoint = {

3 frames
[/usr/local/lib/python3.10/dist-packages/pycocotools/coco.py](https://localhost:8080/#) in loadRes(self, resFile)
    325         assert type(anns) == list, 'results in not an array of objects'
    326         annsImgIds = [ann['image_id'] for ann in anns]
--> 327         assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
    328                'Results do not correspond to current coco set'
    329         if 'caption' in anns[0]:

AssertionError: Results do not correspond to current coco set

**Comment by vfdev-5** [comment]
@golnaz-hs we eventually refactored and updated the tutorial such that it uses now Transforms API v2 (for any feedback on v2 API, please use #6753).
Major updates are (and complete diff is [here](https://github.com/pytorch/tutorials/pull/2533/files)):
- in the dataset `__getitem__` method where now we are using torch and torchvision instead of numpy and Pillow. 
- data augs pipeline using v2 API
- we are using engine.py, coco_eval.py, utils.py scripts from torchvision's main branch.

Evaluation method can fail due to the type of `target["image_id"]` and the version of code you are using. TL;DR, now dataset should output int for `target["image_id"]`, previously it was a scalar tensor.

To make your code working again, please use [`coco_utils.py`](https://github.com/pytorch/vision/blob/main/references/detection/coco_utils.py), [`coco_utils.py`](https://github.com/pytorch/vision/blob/main/references/detection/coco_utils.py) and [`engine.py`](https://github.com/pytorch/vision/blob/main/references/detection/engine.py) from `main` branch and make sure that your dataset outputs `int` for `target["image_id"]`.
You can try to run complete tutorial code : https://github.com/pytorch/tutorials/blob/main/_static/tv-training-code.py on PennFudan dataset and it should work.
Let me know if you have issues with that. Thanks!

**Comment by golnaz-hs** [comment]
It really worked. I truly appreciate your help.

Many thanks,

**Comment by TonojiKiobya** [comment]
make sure the test set annotation json and path are well set. forexample if you are using mmdetection then should be as follows incase you are testing on a test set (modify accordingly if you are testing on the validation set)
ann_file=data_root + 'annotations/instances_valt2017.json',
img_prefix=data_root + 'val2017/images/',

then make sure when you invoke the coco_eval through let say paython tools/coco_eval.py...... then your testing path is well set and it aligns with the setup i have pointed above which is in the config file.

**Comment by devashish-bhake** [comment]
I am facing this issue i have done everything according to the mentioned steps and the above mentioned solutions, but still no difference.

**Comment by devashish-bhake** [comment]
i am working on a custom dataset just using this script to work in it. Just using vscode ipynb. I have made sure that the images and masks are in the right format as shown in the tutorial. Also I tried updating the libraries and trying out the new code on the website of the tutorials and now its throwing a new error saying "RuntimeError: At most 8-bit PNG images are supported currently."
