### ISSUE TITLE
Contributor License Agreement is Facebook CLA and not PyTorch Foundation CLA. No mention of CLA in repo README

### ISSUE THREAD

**Issue by joshlk** [pytorch/vision#8006]
Hi, when opening a PR to this repo the [facebook-github-bot](https://github.com/facebook-github-bot) checks to see if the contributor has signed the Facebook CLA (for example [here](https://github.com/pytorch/vision/pull/7769#issuecomment-1654983025)). Since PyTorch has joined the Linux Foundation the CLA in other repos has been updated to the PyTorch Foundation or Linux Foundation CLA. Do you think this repo will do the same?

Additionally, there is no mention of the CLA requirement in the repo [README.md](https://github.com/pytorch/vision/blob/f96deba0f834d7b9566e8f3c1783d9e0a1c5b5af/README.md) or [CONTRIBUTING.md](https://github.com/pytorch/vision/blob/f96deba0f834d7b9566e8f3c1783d9e0a1c5b5af/CONTRIBUTING.md). Should a note be added?

**Comment by NicolasHug** [comment]
Hi @joshlk ,

At this time, only the core pytorch project is under LF's governance. Other related libraries like torchvision aren't, so that's why we still have to rely on the CLA from Meta here.

> Should a note be added?

Sure, maybe we can add a short sentence at the end of the contributing guide, in the LICENSE section. Feel free to open a PR!

**Comment by joshlk** [comment]
Thanks for the clarification. I made a PR to add a note #8014
