### ISSUE TITLE
Normalize image functionality - Expected behaviour

### ISSUE THREAD

**Issue by Ashok93** [pytorch/vision#839]
Hi,
The normalization of images as I read in https://en.wikipedia.org/wiki/Normalization_(image_processing), is to changes the range of pixel intensity values. But the normalize image as a part of `torchvision/utils.py` does not seem to do so. The output range is not the expected range provided.  
In the code,
```
        def norm_ip(img, min, max):
            img.clamp_(min=min, max=max)
            img.add_(-min).div_(max - min + 1e-5)
```
Is this formulation something intentional or is it an issue?  If I go with what is in the wiki link, something like

```
        def norm_ip(img, min, max):
            img_max = float(img.max())
            img_min = float(img.min())
            img.clamp_(min=min, max=max)
            img.add_(-min).mul_(max - min).div_(img_max - img_min).add_(min)
```

This brings the image in the required normalized range. If it is an issue I can open a pull request for it.
Thanks!

**Comment by pmeier** [comment]
The `norm_ip` function maps an image linearly from the interval `[min, max]` to `[0, 1]` as stated in the documentation of [`make_grid`](https://github.com/pytorch/vision/blob/master/torchvision/utils.py#L16-L17). This means if you go with the default values it maximises the contrast of the image. 

Your modification is just the more general case if you want to map the image to another interval. Since the `make_grid` function is used to concatenate images, I can't think of a reason why you would want to _not_ maximise the contrast if you set `normalize=True`.

**Comment by Ashok93** [comment]
Thanks for the response. I guess my confusion started with the `range` parameter https://github.com/pytorch/vision/blob/master/torchvision/utils.py#L18L19 of the `make_grid` function. I am not sure if the case I suggested might be required for some cases. If not, I can close this issue.

**Comment by pmeier** [comment]
With the `range` parameter you can change the interval you start from. So by supplying `range=(a, b)`, `make_grid` now maps `[a, b]` to `[0, 1]`. This is helpful if you know the value range apriori and suspect some outliers. 

Your case maps `[max, min]` to `[c, d]`. As I said, I can't think of a application for this (which is not to say  some application like this does not exist).

**Comment by Ashok93** [comment]
Yes. Thanks for your inputs. Based on the discussion, I am closing this issue.
