### ISSUE TITLE
Swin Transformer stochastic_depth_prob arguments

### ISSUE THREAD

**Issue by FranciscoPark** [pytorch/vision#8489]
### 🐛 Describe the bug

model =models.swin_b(pretrained=None,progress=False,stochastic_depth_prob=0.5,num_classes =100)
I get TypeError: torchvision.models.swin_transformer._swin_transformer() got multiple values for keyword argument 'stochastic_depth_prob'

### Versions

[pip3] flake8==6.0.0
[pip3] mypy==1.8.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] numpydoc==1.5.0
[pip3] torch==2.3.1
[pip3] torchaudio==2.3.1
[pip3] torchvision==0.18.1
[pip3] triton==2.3.1
[conda] _anaconda_depends         2024.02             py311_mkl_1  
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.8           py311h5eee18b_0  
[conda] mkl_random                1.2.4           py311hdb19cb5_0  
[conda] numpy                     1.26.4          py311h08b1b3b_0  
[conda] numpy-base                1.26.4          py311hf175353_0  
[conda] numpydoc                  1.5.0           py311h06a4308_0  
[conda] pytorch                   2.3.1           py3.11_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.3.1               py311_cu118    pytorch
[conda] torchtriton               2.3.1                     py311    pytorch
[conda] torchvision               0.18.1              py311_cu118    pytorch

**Comment by NicolasHug** [comment]
Hi @FranciscoPark ,

I realize it's not completley obvious (especially since we support `**kwargs`), but these model builders functions like `models.swin_b` are meant to implement a very specific architecture and not all parameters are allowed. For `swin_b`, `stochastic_depth_prob` is hard-coded to 0.5 and it should not be modified.

Since you're not using pre-trained weights anyway, I suggest that you instanciate a model directly from the `SwinTransformer` base class instead: https://github.com/pytorch/vision/blob/f96c42fca53230057b16941b078a0a9eee06e20f/torchvision/models/swin_transformer.py#L508

You might have to hard-code a few of the swin_b parameters yourself, you can look at the code to figure out the values. HTH.
