### ISSUE TITLE
allow passing in progress=False for model_zoo.load_url call

### ISSUE THREAD

**Issue by SsnL** [pytorch/vision#862]
it eats up more than 40% lines of pytorch CI log
![image](https://user-images.githubusercontent.com/5674597/56558961-4b8f4800-656e-11e9-92bd-54042253856a.png)

**Comment by fmassa** [comment]
We should do this!

**Comment by pmeier** [comment]
I would like to take that up in order to get to know the CI process better. I might need some guidance on where to start.

**Comment by fmassa** [comment]
@pmeier we would need to pass the `progress` argument of [`load_state_dict_from_url`](https://github.com/pytorch/pytorch/blob/5f82d59c0ae7d017bdb19a28b23fa1c19a0d6a9e/torch/hub.py#L385) into all the call sites of `model_zoo.load_url` https://github.com/pytorch/vision/blob/ccbb3221b7f0637f1706df29d2c2995e9d5171bf/torchvision/models/resnet.py#L196

I'm not yet clear on what is the best way to address this, given that the `**kwargs` are meant to be dispatched to the model, and not something else.

One possibility is to just add an extra `progress=True` to every call site there. I think it should not be BC-breaking, because the arguments that are passed to the models are kwargs only

**Comment by pmeier** [comment]
1. That part is clear. What I meant is: how do I set `progress=False` for the CI? Or did I misunderstand the problem?
2. Did you choose `resnet` as an example for all models here or is only applicable to it?

**Comment by SsnL** [comment]
@fmassa  do we use master torchvision in pytorch ci?

@pmeier if the answer to the above question is yes, then after you make the change to torchvision, submit a pr to pytorch/pytorch and fix https://github.com/pytorch/pytorch/blob/5f82d59c0ae7d017bdb19a28b23fa1c19a0d6a9e/test/test_utils.py#L496-L515

**Comment by SsnL** [comment]
> I'm not yet clear on what is the best way to address this, given that the **kwargs are meant to be dispatched to the model, and not something else.

> One possibility is to just add an extra progress=True to every call site there. I think it should not be BC-breaking, because the arguments that are passed to the models are kwargs only

yes, `progress=True, **kwargs` should work.

**Comment by fmassa** [comment]
@SsnL not yet, but we will once https://github.com/pytorch/vision/pull/826 get's merged

**Comment by SsnL** [comment]
fixed via #875
