### ISSUE TITLE
support numpy arrays as input (over PIL.Image?)

### ISSUE THREAD

**Issue by bodokaiser** [pytorch/vision#93]
This issue is more thought of a discussion. Wouldn't it be a better approach to use numpy arrays as input over `PIL.Image`s?

Benefits:
- numpy is more general then PIL.Image
- doing some transforms with numpy ops should be faster
- the transformations provided by `PIL` are also available via `scipy` and/or `skimage` for numpy arrays 
- there are fewer problems with using different value ranges, types (e.g. float64) with numpy

What are your ideas on this?

**Comment by fmassa** [comment]
I have the impression that `skimage` uses a wrapper around `PIL`/`matplotlib` for image loading / saving, and all the filters and operations are written using numpy. This might mean that it's probably slower than using `PIL`, which has C code (and which is way slower than OpenCV).
Also, it's probably not as widely available as PIL.

I indeed think that passing around PIL images might not be ideal, but note that we can convert it to `numpy.array` or `torch.Tensor` at no cost.
Also, there is `accimage` in the pytorch folder, that provides some optimized functions for image transformation.

More importantly, I think that we should have a standard for image loading / processing, so that all the models are interchangeable without problems. So HxWxC vs CxHxW, RGB vs BGR, [0,1] vs [0,255], etc.
Using PIL is a way of keeping a standard, so it's a good thing.

**Comment by bodokaiser** [comment]
Yes, you are right! Your arguments regarding availability and having an image standard are convincing. 

Regarding performance I only found [this (pillow-perf)](https://python-pillow.org/pillow-perf/) unfortunately it does not compare with skimage or scipy.
