### ISSUE TITLE
Memory size occupied by fasterrcnn_resnet50_fpn?

### ISSUE THREAD

**Issue by cowry5** [pytorch/vision#962]
I am doing a object detection task and I fine-tune the fasterrcnn_resnet50_fpn model on my own dataset。
```
GPU: a GTX1080ti 
Memory: 11178MiB
```
But when I train, I have to set the batchsize to 1 because the model occupies 11g of gpu memory.
![image](https://user-images.githubusercontent.com/32674827/58424349-d1e8fd80-80c9-11e9-9bbd-e5c93490cd25.png)

Is this model so big?

**Comment by fmassa** [comment]
You should use `torch.cuda.max_memory_allocated()` to log the memory used, as just checking `nvidia-smi` is not reliable because we have a caching allocator.

Using the default configurations, `fasterrcnn_resnet50_fpn` should use 5.2GB, as you can see in https://pytorch.org/docs/stable/torchvision/models.html#runtime-characteristics

Also, if you want to save even more memory during training, you can make all parameters of the model, except for the one in the classifier, to be `requires_grad_(False)`, this will make it use much less memory.

I'm closing this issue, but let me know if you have further questions

**Comment by spatiallysaying** [comment]
> I am doing a object detection task and I fine-tune the fasterrcnn_resnet50_fpn model on my own dataset。

@cowry5 . Were you successful in fine tuning  the fasterrcnn_resnet50_fpn model for your own dataset ?
If so ,could you outline the steps necessary?
You may want to answer my query https://github.com/pytorch/vision/issues/1071
